# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
  name: ha-token-secret
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:v46Jd2usWpCqHTkBfD+kn71EnaMuNNIhRftvtWJo5GLyrrQFeTu/JNAQ2PcdYWm86zwXYb9Df0m4QJfxtlmlfwo8Uy4JWRuPreU36ODqoMpCuhx6ntOWxn9HoOUl+uis+mn1LrsfkHD+kY7JZV98Ty7eluKLFOqVxl4HhUcQiUClu3pOMcDaP8PfwUhEGd/0A+vBZca0JMZo9bL1ykA6rCPlJl4Nv3Kv4AurTyCh2UCnTxS/BN+c,iv:Yo+dz0LL0ABHM5xG6yyim7XGFUkBA0fSkvVKQR2/XFQ=,tag:aWWUuX/GaDWCUhEdIHi46w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQkNvR2RUQUJBVFpwZ0J2
        aG0vN3NRVGMwNE1JRUZ0TGFjdWhZU3d5Ym5FCnhpZ2RZL01ham1zV0pEWmMrNFBM
        WkpjdmNpdTNWQXBwYk5ST3RXYTNCUk0KLS0tIFVHbGJZaHQ3dVRYc1VTNEpZMXAx
        b09KS25YdysxbEdDS3hqZjVIVVZDYTAKdlszrvHlltFXSbanRTMH10RPMY7Etw5z
        Az0AlGLUVX2IDjWb+FymlcMVVoVj5vvm8UH8YTlqmOsrTZyDcJprnw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-24T10:05:54Z"
  mac: ENC[AES256_GCM,data:gWrjzfOywJ7ixTvDzgGCJQ8VmLZRz8d7Sm0vK4Qb0uVId8XMqEt7KzbOjhmGfxIbx4koTcmv+dlNIW4VEG7MBoxp0NaWzSpbL+LaR6RlpceGbTS3ucRF9eZ02N2ZVSNmRRvA4CH2zlQ0z7mxqenz2cmOM3KupsNviW7JkoiPl7c=,iv:AeiMtVK52i45bvmK9LdigWV/oDYCr4U/OzNrEFQFkM8=,tag:lcPxmu7qDvv5XQlDo4cUjg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
