---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: music-assistant
spec:
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
      version: "5.0.0"
  interval: 1h0m0s
  values:
    controllers:
      music-assistant:
        type: statefulset
        containers:
          app:
            image:
              repository: ghcr.io/music-assistant/server
              tag: "nightly"
            env:
              TZ: ${TIMEZONE}
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              limits:
                memory: 1Gi
              requests:
                cpu: 15m
                memory: 512Mi

    defaultPodOptions:
      annotations:
        k8s.v1.cni.cncf.io/networks: network/multus-macvlan2, network/multus-macvlan3

    service:
      app:
        controller: music-assistant
        ports:
          http:
            port: 8095
      streamserver:
        controller: music-assistant
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: "${IPV6_PREFIX_GUA}:2000:0:6:15"
        labels:
          service.kubernetes.io/topology: external
        ipFamilyPolicy: SingleStack
        ipFamilies:
          - IPv6
        ports:
          streamserver:
            port: 8097
            protocol: TCP

    route:
      app:
        enabled: true
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Apps
          gethomepage.dev/icon: sh-music-assistant.svg
          gethomepage.dev/name: Music Assistant
          gethomepage.dev/app: music-assistant
        parentRefs:
          - name: main-gateway
            namespace: network
        hostnames:
          - "mass.${CLUSTER_DOMAIN}"
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - identifier: app
                port: 8095

    persistence:
      data:
        enabled: true
        existingClaim: music-assistant-data
        globalMounts:
          - path: /data
