# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
  name: sure-secret
type: Opaque
stringData:
  SECRET_KEY_BASE: ENC[AES256_GCM,data:vGGKQKiLYR2YH+MbfWrz7bT8yuchU/qEOZmFH571/C6vOYEgmWVkDF4DCO23wIVm5tQI/alY9MWsM2hweG0Zy4fUvFb/q79YZiWQviM28Bvn7SC+CAtPfYz+2BkaOPojNepX3GGEtyK/EWLOrqYnNJNdDF4fOU2tdCDdrW/PXX8=,iv:53Pmb2Z2cd6GwLz1DqbKLpD7zEif9aeE/KbfYRhIfYU=,tag:jvqPVzVub4KpqLAPcQPUcQ==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:3BEW5nsr2W+JUQ8L5F8sTvf8cMVCd2xFKCf4QhFCxGA=,iv:PSVPVYKBkT4kks63m8694svhr6yV9KxT6bGdUAxPq4E=,tag:hRtGgEJ/jojl1xQjkPrnJw==,type:str]
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:pcE5FLFmkq3qCU0YJM54tWgs3UDiaZ8ZzPIFGcQeMvWdwGhW,iv:YNIl3WjgdJjsQbCXBSYvjpMj0iBI3DdObMz3vTFJSE0=,tag:EtFLZm/yGQjov+5jXkAZsw==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:bygziY3oaIGfi0IAyQqcgT4jEQejU4KZOHjxzD8AUSE=,iv:4lmzp6tdzD0KtB2NoVCIig4EhVBz83iYFcNd/8RUkOU=,tag:04YLe3OziwfxHCeF1blNTA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbWpXTEVLUWhwL1d1VDJC
        OHhVem5leUVRNWRIVDJLOHZrb0o3N09CQlJvCkI4czNtbzhDdTlLaml1U01uWHVY
        bGpFeWxXdWJzZzkrR0VYcU50clZIYVEKLS0tIHNQczdVNzFlNlpJUmxjZXdpVlBv
        M2lId0R0U2FZaVRsdk1xNDhCeW9uQ0UK5650/TcwIt8L6PMlo5qQuoUG0XvOrK/V
        3uhE0+npEYFj/ZdKa2gE9QbjFDr3VIBgLSJGGFUwfY3yoKNkxk/koQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-04T14:39:09Z"
  mac: ENC[AES256_GCM,data:b4aXyZZdOIFWk8xNyKHriYVJsQvhzh+NKm2V/4ITBPaAYJZEX+kL3yl5i/OuHpO4xGSwol1TtbCp00zBkNsJWMDsYksPmPFM82/j0a7NhI4ZOHOH29TcVHt9utRhok+9f6OqJtFCKTFjfXA/7IW88fJl/1shJLHBuuFNQEfkH/s=,iv:DQ2gBac3j/uwNPaHfYRkTKSC1RbhpdZDybN9qaU3pew=,tag:Uru2vzcoAUdaTQoCHgBmcg==,type:str]
  version: 3.13.1
