# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
  name: sure-secret
type: Opaque
stringData:
  SECRET_KEY_BASE: ENC[AES256_GCM,data:XcjxvkdR1kaCynOqecp7KQ9xXT8Ij6nApG+GZaHgocDzmun9j1M9ROspwbIQvc4/BN7NYloKEnOfvlMEjGeohPDCTBqn1po1HWsUHvJy6KQJ/qVW9M+6TmwDNnB4aflr3AdgyuUNisZCBd8/4wr4qIhKbZwX5y6gFIgLEaWLsJ0=,iv:plngIItai67MqTF0cFejRutcx/5NJoI+jPrT+QCkTJY=,tag:w5tHT9p2fJb+Lbb5JDC/Ug==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:e8BHRNYhwzb9s7l5DSyCJtlEzhQ6LuElbtUFgLqGkLM=,iv:pgRLw6Xd6anghx338rUl/oGWBkSNE4DW+sqFMwviCg4=,tag:MExVb3LhDCDtj3hp/dDOGg==,type:str]
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:O1GvPeH99jEONm9XeQWkIwTwG4Jp3PLTQmIvX4S1vAsNMDjp,iv:t8flKe7553uk+tkbvlFXcbxybzDgTcTdcXbKXiibBLg=,tag:dZ1w1WjwlKZsDwSh9YeXjg==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:EWPYa1k15rLkYeLs4W4n7z/JwksrjPNzxjAicF0Bg1s=,iv:twwX7rhGGD3c0MwmCURbSdSZbGDPTqeGfveI21DT/o4=,tag:IcGI2A5Ni4nfdCrIBrh77w==,type:str]
  OPENAI_URI_BASE: ENC[AES256_GCM,data:NG+O7xQRf6I2Qt51oeH39aUWcVncQAvthd2NtV1QzDPF,iv:nkpDX25zo+H/2J+i8kGg0xiLzQaP51KvTU2GJgls+zQ=,tag:LMsg4aB3RpNj5oeeJcvipQ==,type:str]
  OPENAI_ACCESS_TOKEN: ENC[AES256_GCM,data:WZj9g0Hyt+fxsoB/uZg9Uf0AT/71KfXr4X1qVH5Arlk8bfk=,iv:HsigC2x11ShlLDffCCBJTmnSQp7bOIUUrrhVttHQmME=,tag:RWj8pF2kunq9XzKC2g6uNw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZ2c4NU5jWDNORmZoTUFW
        WHVYOUNsYlo3ZHJQTzVQZk81Q09hVEhHMlg0CnJrZnBoVHpCUGFnQlJvSXdPbXF5
        Qkt4Q1hreVQyT0x3SEtDZ2RHZURmUFEKLS0tIEQzdDcvVS9aTWZENDR3cmxYc0Nr
        Q1kreHJkLzJqYzVoekgwMTRBRXlXQncKsDtezIEVYPLhoczb1XX4rr9mXFAtm0J4
        seOaSQy7wzBcxXh4Ghv8iABepyPxASVMHSlG1Dby9W0Z1ciW3Vggaw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-05T16:45:39Z"
  mac: ENC[AES256_GCM,data:kILnOFo3D4B6if6ydfcWV6LcoPLR5ldyQ9YK1JHt5cuPb1wNTJbS+sNFFKTVsRDTL0QIUf2E84V/43fI5GWH5SPi3/sMJbTRAszrKNjYPw/kUsMa09VLjT43Tez4TqS/tI9PWu3mCZwRXa2DyS48om+QBhhsECq479p0rRabqc0=,iv:QVH9lzThmD9kRyTMabuF+TX7nQaON3rinsLeCrNsmXA=,tag:KT/uf1g70qrUVRMxEJl9zA==,type:str]
  version: 3.13.1
