# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
  name: sure-secret
type: Opaque
stringData:
  SECRET_KEY_BASE: ENC[AES256_GCM,data:k1zyGT/N5Hrxj0D3i4X7Pd1mOu/UkPGiXLBrbj4oagVL4Dk2J4hpUK53qwAeSZ2Cw1fXPWVEEXVFn8m2IYucUIJna+miNhP9kK6LuSZgZ5E+67jtD5wVh+VvmStDuvmGaf0FWWK02vCC0gCYxil6KtxSF6ONkAcKAU7lM79veZ4=,iv:Xk5NIrsL5eGdHMTjTS4l0hT8Qny08eEEuHSMbCM4Iks=,tag:hNDMAiVmIuG/DFhh2NpoOQ==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:ysVdSm4qb4SyFZW4t1UaKONo7yQ3oiH7efFjI/oGQBs=,iv:7UmfByBDMWZd1UfFJ/6gbb/5TLR5BVymnL0ATA9nbUk=,tag:C/EXuF2Tyok1x0HcSVvxuw==,type:str]
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:4azsdccXndmHU0AzByUIyvHMvr1ErALg84yF/0RmMCI96vE+,iv:/agUjm14l0z9uTgxSjaFw+t6LMjSi8hoqb6dZ2qEZ1A=,tag:cKh0ABStjHZIkCJkKFCg6A==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:FYg18fa1lx3zzHFtggKGOkUe1BjS7IePCTOLbuoSca0=,iv:0144AYOVeXnRI9sPWkE4v0ytkTSnFVfsImzYD7IRk4c=,tag:RqiVqFcjbjV8NXqeQK7E7Q==,type:str]
  BRAND_FETCH_CLIENT_ID: ENC[AES256_GCM,data:G6fUujGtcxWbQ2Koi2mpEGLNxQ==,iv:jfDiuyGzRPYn4kju43oyCzV74qwVR4oSA939z6LicNc=,tag:Gb9c2/ouonzzHkE9avPyig==,type:str]
  OPENAI_URI_BASE: ENC[AES256_GCM,data:my6zAmwcXeMQJD9FSqCosuYbjHWg6cGbdvjI7f+HiM5J,iv:8pgGQ/2eX/WKXXiqcMjQxYGySgSUdW4lLl9/eP94QtE=,tag:Aze4myXTn8mfyuHd5Wz46Q==,type:str]
  OPENAI_ACCESS_TOKEN: ENC[AES256_GCM,data:Zn4SzjzD,iv:3tpl2fGQmQz2nNNGT0TaYQGY3JUVKWC6XNMZBKMiki8=,tag:DHmeiiGCqv21GJ1xO43gLg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTFVTN1lQY2JOajJXTTRU
        UDZGZ3FaVjlUOGNOU1hoclVGRC9LdGhUcWxRCnFIb2F0UHo5aDBNRHZCZGsxL2dk
        alZaM2hxUlFmUDhmQ0tWd2xTTTBoeEkKLS0tIHNDZnduMDNWRTNDL25ZME1acFYv
        dVNGVmdPczBlZVRKV3hsSm05a0RIcDAKpkMxYessFLWFIEgcvZZ4jMgcdzHfXsCg
        KqWp/LN4boWhpUeo+ypzbzkYgJSh+KopKLlaM82+EgCcEjycVFH+sQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-06T10:20:42Z"
  mac: ENC[AES256_GCM,data:9Ntca6D6ORzrWku78VaTPQY7ohZ08oD6wk43biSAbLuZd0M4qT5C9sDQDl3dWHG8bi8RJugiOXbfCUXZ2h7g+jsRBNiNWUY/WkcfWl9ymtYQEZSzEiTdHUwFz7xuJd2WduNxuyOqneaq/vbg3C32uqP1bs7t61x0gUiPOEa6p7o=,iv:gRcbtw0y+dDhSchbYZe32cO8SCs9FHLr310BUymZrIM=,tag:Viq0k72/eFKzqahzsR5K7g==,type:str]
  version: 3.13.1
