# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
  name: longhorn-b2-backups
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:h/oCGuInS+kVUJyO7pxcADZEgFYwiexgdw==,iv:Xyhz81yrSZ/1N2WxCczFBYgnm6nOqIhoYhvYuYPiPTQ=,tag:53bpPi5n/S+WwOp0NXT69Q==,type:str]
  AWS_ENDPOINTS: ENC[AES256_GCM,data:ch7EalCEmgQlRVWekwZ6jac/oluPrskOamHf0exUZpmO1XZyasWDcS8=,iv:YAoafx0aDMlaGHSpW2+YrqvKOZ8L54JKkV/xriP0uvc=,tag:bmv2sL4C1tD318Gs2wp/1Q==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:n+WXpRHCeJJhWavTfKcuKRWlPdcUdwrlQPRAJm9YeA==,iv:86MsasGHDRgN5rzDg99I4btRqn0VoCKvb/oALLCpOJ4=,tag:jEpfpfZuoq3bFkgttYRR3A==,type:str]
sops:
  age:
    - recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQm5BNUladUY2Q0JNbEZB
        bE5CTzUvWWhoSmFmV3AvRWhSVUNYem81N1hVCjdLdGlNTDJLajlCdU9aQzlrcERK
        MUpxSWo1WkVrb25JMzFKVGo1emNpaTQKLS0tIHl5aXhYdmp4MlUyNUJmR0E0UzIr
        dVNkY1M1OTlpY0JHV1BFSFZpQ1hHTWMKO2w+O0bOm9dVmtrxb/WPIVquw0wcwGlr
        ynUhnHIZ8OKIfTCQCj07wgl+I2zJ0ufS5yzRJqz7ksv4ubV3cC2v7w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-30T12:06:01Z"
  mac: ENC[AES256_GCM,data:u96E2QJhNVb8A0N0/5VpmFdLyZOFvtbKRUwW22vm1C+gfmzEX3XghNR0tecn+FtdvHbA8rNfoz/9qGDDvmNftX1X81f5moamSa7i0LfswtPL/8mokeQhJNHC2r5Ed6xpiP4hsDaXPeRf9hkLzc1g2hHC5xfNUOpmFc7H824/KM8=,iv:d6GsqJo4jCW0FdtEH3ZEqxah+6rQE5K4uQsAuc8vIM8=,tag:qmWrR078CQXww1azp3+1rw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
