# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-secret
  namespace: longhorn-system
stringData:
  OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:+8PpgTh69V3K5eRuPaTVQuDh79oihxi7wF11KmMYuP1h0iY3,iv:F59juMfSsVlCKsICyF+Au9utOmk7WvdL+kOFoYn/s9w=,tag:5AwB9kZuTQazxfQW6f76Kw==,type:str]
  OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:VtqKydzJ2Rf3KiYGLIahQCUahOOdhbplYnCxqQMqjBQ=,iv:vpRm4LY1Muf+ZOApTL/h19sTOZVTLuF3mjB8cu0FUYE=,tag:ZFa83NVa5tVgToZ1rdtjRw==,type:str]
  OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:MkFwWtqVQqH3h+7p4J0mPCdh7GzIvlDGWpkCpRfjQYIvvnmC2XQQugTzcfs=,iv:8Iqh5j3N0L2mGxpgilaNQm5MO2i1AQgxElkuhDm32bU=,tag:/gTXEQqJVJScwxHgUbgoOA==,type:str]
sops:
  age:
    - recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUGZVTTJJeHlhUC9ycW1v
        RFJiaHg4VzlmK0Qxc2R4Vng3ZWJrWVY0QlhRCjNIaUtWUmpVZExwY1NpVXA1QUNE
        NnhUTU9kcEZ4dXpKZklPS2RDRWRtSU0KLS0tIEN1dmJ6R1NGdWxaMUt3bkRWSnlO
        VUkxa1hHMzZTelJCazFxb0Yxa2pXdHMKAkjYU94LfCi5p/rH24TvmeBnk97DDCRj
        AiZwniaSq0D4kk80tE54mP/zitFf0ZojoPh4yg1u1GMny8zhuRjOMQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-27T10:17:08Z"
  mac: ENC[AES256_GCM,data:jcEahYExz4bFy3/oCK0ZOQN8fK/IOuqI6nnWbacFdIk2beMiYaSh7WUe6VV5A5YfvJrpbj9sgUw707ylIEircDCN/QcJ6ZYE028OLk1IEtWKXVffPy4/zXSEGfq/P7rQwAV9Hzq9lSSTOeNRWn7kr+/HwJzuaCizZwzWr8edmWs=,iv:8mKDIZjC0EIQXIExzfBQSvXjTDpR45fwWapFOb2Tkpk=,tag:+ACJnSJ0TRlNZS2BUeO9vw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
