# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
    name: radarvirtuel-config
type: Opaque
stringData:
    RV_CONTRIB_EMAIL: ENC[AES256_GCM,data:RipFuv/V2ZUnggy2tQ55BfVIHrHnPB6YuA==,iv:38PJb0kGHGTf9ALijFt1k0e8qFOmkfYfI8AOQJkzlIg=,tag:PkSCwMHRNJDpNma2lLXuqQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZHFYUmlCcG55Q1cwMlVD
            WlhBTFBDeTMxUm1mQjViVzJ0dEIvejNKSmpRClVCY0d3ZHJkNHlFSzRQUDFqSkQ2
            VzdYVGNlYncwdlZKYjFUdDBoalZzN1kKLS0tIGl1TWVsdTViOS8yajZ0NFkzdXlU
            bElTOS8rUHYwVVdZeStuMnNIdG9UU2cKQ15+px4tviUh5TVQyq2YTb0jfZRVCbgh
            B+3yd4fIkJx2hO5AUiZbaEeJqxvMjiHR6hSdFOtB6ZmA/5Ua/+gEvg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T20:35:27Z"
    mac: ENC[AES256_GCM,data:AcPBjPRK4N2acvcWKCo/JkDEoOXvBkbvDeJT1E2vnZf3KAV4hmoJS7e6Rm9tRA+NghY+a3xSQBtl2gJUVRLQtM/OgSG/CsmLLKaTisl25jBHYIAmivtc+SMqq2lWqZGwqZhzwF0H6mgx5Uu7HcvnxMiU7RyrJ2HlnftsUvYBW08=,iv:MNnpOo2OgH2JEppiIOkd+TiPXUJofQuqYhR+32HP26E=,tag:gC/5nfy1jZvT9M5t2WnT9g==,type:str]
    version: 3.13.3
