# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
  name: netbootxyz-oauth2-proxy-secret
stringData:
  OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:NQiZNokmvAVMDVHhxQNYGHUwQMq+THy5a7Wch9BSm4iPMvcr,iv:Ex9fySEanx+RsCJCDN2mbXtS+nmov4VgWkzAJPX208w=,tag:A+h6j+3z05kbQjQ37zikxw==,type:str]
  OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:gluTJVphqRVkr5wqtAJw8+2XvYWQHkDbyktdHzpZXJc=,iv:BZQQC3EIGUi+twG6kGn9joaQzYyMiG7+poXshMU/zXg=,tag:yorOPw0fEuofPGN3aU8Grw==,type:str]
  OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:6P646b4z/0Ne5kniYMrFqN3NlHXzmlFo51NIGgkkfb/rjWsAEcLo7S3GdA0=,iv:cTBwUucJC7vMUVFYO1q87nImZymxSJQirrYKHR5+YsE=,tag:v2h4csHgX0cgmVodQTTzsQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZmk3QnpIRDJtZE9jWVRP
        OG0zTjd3VnRmT1QvbzkveWl4OStvYmp2cWpjCk5ET3JSdEE3MDRRWUI1TmVJL1VM
        c0Y2cXc1U1BtZGhRNmcvczFzNE91UGcKLS0tIEVTYWdXV2JDeGZhVCs0KzV4RXRr
        TVhUQUtFZmxGaGxMdlNzcWExcHdoUlUKcqaIrU+MnWd7fou03TWrsTqt/CGZXGxF
        xGOv0RPI6EOu928p6kgXhjOueEhZT5vnWdGil6zj5tIQZxp8+hQh6A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-14T17:44:26Z"
  mac: ENC[AES256_GCM,data:TAdka0W8gtsc5O5ORiE0Vg1NQ95CW7ycTjT6itoNiGF3MjjLWt1ID8XgQgFRJqZnNUm1p3obus5qakGunCQlXe2jZ0x1xwSO01GlA/qpnyt/1YKXz+xn9RZtvMhM0W/cBH7OIFnO0b674vmoYaTdDO80hf6ZMP2KGXjuwfnY+EA=,iv:KdV6uRezoY0zQL5ILDqwPsSJ2CZ9fJ3GCEHsHfK4Dgk=,tag:scZg3J9927n0ShQC7oGppQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
