---
apiVersion: v1
kind: Service
metadata:
  name: netbootxyz
  labels:
    app.kubernetes.io/name: netbootxyz
  annotations:
spec:
  ipFamilyPolicy: PreferDualStack
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
    - port: 80
      targetPort: http-assets
      protocol: TCP
      name: http-assets
    - port: 69
      targetPort: tftp
      protocol: UDP
      name: tftp
  selector:
    app.kubernetes.io/name: netbootxyz
