# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
    name: piaware-config
type: Opaque
stringData:
    PIAWARE_FEEDER_ID: ENC[AES256_GCM,data:T7OrakK+RDIyyE94EmS4zKKQ4YzwIaCiSx+5Uag/wZHxNk0F,iv:smJ6i53ce9YIn97HYZsibi1QoTzX/JVWmKYfH2wavRw=,tag:+Db3F0mSTCpByqOarZoFFg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWDRYZk0rVGpyOWFkYkI1
            WHpFOGtaTlI4VGRWOVh3Qkw3SWNub0NQalZrCkhyZ055U1FIWUtFQmszMUQ3bGpJ
            a1FOMVZvTHVicm9SL3FuVlNjbCt4bkUKLS0tIHhLTEp6VExodjYzNGZRWngwVzha
            NFVGSlRrb1RSWThrbHVkTXp4azR4RW8KrlK2bbwuwApmJf39qTxt1AsprZ6HsGnr
            ++BoLSuRj6OM6/eHRd0ZiYbv4yihD+OEDf9peObnB6D0PdGerno/TA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T15:12:39Z"
    mac: ENC[AES256_GCM,data:omVFDo4f0DSaaiOABEV8iXPizQp/kXXuTRB5sg2WjUB3TGs1UoqzRog1THPvjBx75UtoaKbRnOzGEDGnJo7PPXtytRAt9z9ls4cCp+94fAWuYNO4lH9Z0TudT1ZWdd2FMdmuR3lMWf3EmqIqgd/i36JF4qZ8iamOjWzjTJnEf8c=,iv:ejxxPTbRc42n79kHBnIn9Nkvp3Gdrijrt8E+5MDiJIw=,tag:+3GxHXYeYn+eXkevKpzW0w==,type:str]
    version: 3.13.3
