---
# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
data:
  mosquitto.conf: |
    persistence true
    persistence_location /mosquitto/data/
    log_dest stdout

    allow_anonymous false
    password_file /mosquitto/secrets/password_file

    listener 1883

    listener 8883
    certfile /mosquitto/certs/tls.crt
    keyfile /mosquitto/certs/tls.key
