# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-auth
  annotations:
    # The $7$ PBKDF2 hash markers would otherwise be eaten by Flux envsubst.
    kustomize.toolkit.fluxcd.io/substitute: disabled
type: Opaque
stringData:
  password_file: ENC[AES256_GCM,data:A+GKaexThS9YFP2AjG7PzciSmwcWRwrDecxAgEj1sAmKo0lbeIWIh5IC5FM79mBjHe/adIOMbZPZ72+Cfo1YM5TfdUUgymJWQv3FrpPZk2gwV7XxYbXaOT2jcls/uZwnh7iJiPa3wGRL4eqjcLsZKPlHnT6GrR879xRebN9AVFJSWCTwaqvMgffPtr209cnL5jrBu/Vp6UjrCWdqtKSKUDqt4vDvHWyAAlgzhrFlxvPPyvHcCCJuiInnZ30nK5KXCK0h2N0r2aoYHAA+TLSeWpTRHQYf2kE4UgK3znggl8Ho5D83Knt+3EhwoCFG+knrz47/1TrCRpw=,iv:fq0KUqYIhvL2M4OEyvXjSLHVbzZ40nUCAyGzN9aFGsg=,tag:pDh7gOJ3DUprVg6BkKwE2A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXVnhZWTdvWThZR1FXV213
        TldsYXlORFFNaGVtSzlmRTF4ZGl3V0hGZWg0ClpzZE5YYmdxTEVsNytjbTluckdZ
        b09EZVhpSDJTRGEyKzVFeEkyczlhYnMKLS0tIHM3aHhtWVZZT0M2OWtwak9LUXlO
        bTNzUXArZVdIZ0RtdnYrRCtkZUNDWjAKZvENhhCF9IdOHIFhpeHLg1AzNpYJtYqX
        Sq8mj4dKuOBZnZWkdkPZhMG2kuMOmaGEMT3fCFfZ758/VN0LRXrZXA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-13T18:31:25Z"
  mac: ENC[AES256_GCM,data:6LB3QESYVtkZcgC+xkMGTkpMJ6CXMcOsqntNKhl5nUOJhbG35oNH60iPzjhUkfDpZBh0nu/ET2JpAKCyERBhW2c1Wy/9qJuPYt7o0E2LFlkfLRNjtdMRsYpVlG7tC1tlSFM7ldmBpggGqAU5UI34XNQ90XQyUuYHqLVuGrWBCIE=,iv:AoSDmeE4svWhSkwecRuJqGz/ooy5Y6jGRtIM0Yrnahw=,tag:j2DQyY1Pf8/Q3Muav8KTHA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
