# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-auth
  annotations:
    # The $7$ PBKDF2 hash markers would otherwise be eaten by Flux envsubst.
    kustomize.toolkit.fluxcd.io/substitute: disabled
type: Opaque
stringData:
  password_file: ENC[AES256_GCM,data:xzP9ANQnq+shrNiuFXR8bBokFcyTU4zuemoqVya/jker0tO2ngvsSuE4Aka+BFhe8LrXCc5qvzr3FA6cdmcSptKH8cbGmNjSeueLnintQZqvlxq/OaZy8XX0AzGjytqqJxCvleLNsy6if8GovIGHFui4rGvbrvKUZ9rhdplFwgjZmc7dMipSoxmV7/5GkpG6qckU63ntwoogcGxtagkGnnfTty/49EijC4j2TE28iazR82/SVj50ipN7IO4Vl6dlhmk1XjHxzb4lWH77TPJ4qGkshfPSgdAnpDBfOsXTlOpzYB8ChnDYuYrTgggPR8bfio6S1FPipqZIc3vB/t3Lp4mLY4k8eII61ihz3Ky8RaNErGW5xqIWJOrXrzatUnXm9zlpQmjLLnyYIh8iOSbrDlvivt9F87/BSvCWpnkFdsLYRoKn6WrXchju8XsaZ6sEFNKAABt4DG0yzTVQDy0Nbs8oT5iouD7M1C6yPbx+eyzS,iv:uDaXzHW7zC5h83d6HYIOtO0tu9ypP3Os2GB06zbPlpM=,tag:rr3EAw2DgKinMJqr3Kua2A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzOEZka09aTmlNcjdRa3Bo
        WEcwTHhuaGo0TDY4K2pSNW53SEt4T05EdFYwCmJxUlBvU3dKbCtyMFpNZ3V3a2pO
        ZXArdWlJdS9jaGsyNHZRRFkrL1RkbkkKLS0tIENOeC9vK1RDYzBsdXZHQnhTSXlE
        ek16cFplb2JrTDIwTjhmaTFHaW5sTWsKj0QdKhGNOuc3PWneF1gabPrNXOJKV6n3
        F+yNG7Yn+l4W3YIlz2StHJWx1wciln1BiSx4CazLKZYBVZ0Y0Ao3Fw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-13T19:35:14Z"
  mac: ENC[AES256_GCM,data:qZGEJgO8m48qeP/AeeTWlZdIcqylEBCRctouvUJCdehIwg+WBMinAR0ZavK3nW/wmE6SOUigUP4ctdVWtfO8/Pule1qKVNoRWOjCRabUrDWMyZxnqFdn2u4F5yxV41ycKZA/d7dF2TorFreN/Z27jHA5jnpVIzZHrY7sNxtQcMg=,iv:EJVmNTUs+r54f4DtpSM7pFQajSH4W4PjvKlkAOcaQPU=,tag:TH6pgkzhE2utKxMhVUv2TQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
