---
# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-mqtt
  labels:
    app.kubernetes.io/name: mosquitto
    service.kubernetes.io/topology: internal
  annotations:
    io.cilium/lb-ipam-ips: "fd00:1018:0:5:3000::42,10.18.6.42"
spec:
  type: LoadBalancer
  ports:
    - port: 1883
      targetPort: 1883
      protocol: TCP
      name: mqtt
    - port: 8883
      targetPort: 8883
      protocol: TCP
      name: mqtts
  selector:
    app.kubernetes.io/name: mosquitto
