---
# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
    name: skystats-secret
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:c5p9YihxlWUPCxcP/pGIRHNWFLkYizEnbHlRvMNeoiA=,iv:juEw53RdxUxBWok7FNG10cFTt9m4W1jd49th1eIEFik=,tag:2RknfEg3iX9tTK5I7SVrCg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISjlYL0VQNlYyMTEwNjNX
            OUpjdWJuWVY4L2JXMytzQU1zZ3l4OTBxQjFvCnNWQ0toUnk5d2lxano1UGYrcjRq
            ZTlDbFNBb3VZQ0UzL2V2bUhJendOT1EKLS0tIHR4TC9ndlIyc0RUdThSVVMvZG5Y
            bm9qclhnamp1NERlazBaL1o2Q1lQUXcKyDlUmiIMSiQe7tQk/Ml/7VMtZ3jyJkeV
            LqelR4bJRuuxDZt+gmF631whiP3xtyeiZBODCDru8yhi/hwNRW8lmA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T13:00:24Z"
    mac: ENC[AES256_GCM,data:+NRwr0geKMmlCSnA57PzN8q07aCXWU4dRBpqZ1IYaM/yp2PpZIy+H+FWFmwCybdtlVvJZIihclo0Z3HIXGlURw4VUkGTubrgKqPf0j4RYz83/dB9EsQWSy8mkIlUfhveciL+Ysl1tUZvmVVyeEv++DgihaF43U6WzG8x80NysZE=,iv:qU5rhKnyo6omcr6LzJ8KwxxTs5hcGP/R/+WqdO+flyA=,tag:BHoSof67EHrCo5Bss4GHGw==,type:str]
    version: 3.13.3
