# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
type: Opaque
stringData:
    smtp-password: ENC[AES256_GCM,data:6qQ9WqjfcfCJdG1YwFcHEb5/pZO+owd/22MAmYiuOf6OAGn6,iv:J1Yrmq6YjM4j1JXgr5Y75OjJeTm+NTNEQRKx03eYVHo=,tag:bYtrhIY7jTueS+qnVTgrtQ==,type:str]
    ntfy-token: ENC[AES256_GCM,data:oig7clUbWBLldecLUndInyUa5I+dlL96UrD8efiwPjU=,iv:6mIj3C75Ol0vPDkl7Pcivvag66LtvSpkgPQ1hpA+BGs=,tag:IxgMTJNZdkGFKQEhc2Beog==,type:str]
    healthchecks-url: ENC[AES256_GCM,data:8BEnbO13Fy7Gdco3uHrOPHoykAdBwEqeh6s+j2r2s6Xo4kQFsEmIQBx2zsB9Ra/t3VuGf1Qm0sg=,iv:TwK61ufvhVsokx2YCN4XrJQrUnxJWSWFz4I+m5RQRGw=,tag:OWLBO+4spTe+OKgp9CH58Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmTnJwL3BFcnNIZThBNUJG
            YnRvUzZZTVVLQldEQ1BYdVYxc1NUTk1iNzFrCnZqalBlNkZwSDBWUm9HMWVDMEZ0
            MUZlTjJvK2dWZlh6a3k4b1h1V01iU2cKLS0tIG1GSy8rMmgvMDdlWVphMWIrZWFD
            enB6akNNbUY3ZVZNVlQzS1Z1enE1TzgKPv2vZGNCEnQ+qgX3glyTdueEPZNl9ZKP
            w5nHZG1sDfOi+0aU7OP/WfbeIs3HjenAXzGApy/e9LsEtcYi8kbVhg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-11T07:20:56Z"
    mac: ENC[AES256_GCM,data:QULoevVQA+g/wUVsEOljFwUe+fdRvg+T2sMAMzgKAQw36gRGaekuS8wOeUWioDHXfT1RYFwbXbOyHdW52mq7fo2pIpAUBKPL9HYjh8TUWKlccwEKEzzJP8bvCO0KzKIiWInMnirp9ZsKWhkf2FslC5bCTHguHjTJ1KBSVc3Dj7U=,iv:mV1Uc+TxRks7NMtNy2AmeSjfiCfRPujQRI5VmNYGzcg=,tag:KfbFFBcBtO8eDolMB/ngKA==,type:str]
    version: 3.13.3
