# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
type: Opaque
stringData:
    ntfy-token: ENC[AES256_GCM,data:oig7clUbWBLldecLUndInyUa5I+dlL96UrD8efiwPjU=,iv:6mIj3C75Ol0vPDkl7Pcivvag66LtvSpkgPQ1hpA+BGs=,tag:IxgMTJNZdkGFKQEhc2Beog==,type:str]
    healthchecks-url: ENC[AES256_GCM,data:8BEnbO13Fy7Gdco3uHrOPHoykAdBwEqeh6s+j2r2s6Xo4kQFsEmIQBx2zsB9Ra/t3VuGf1Qm0sg=,iv:TwK61ufvhVsokx2YCN4XrJQrUnxJWSWFz4I+m5RQRGw=,tag:OWLBO+4spTe+OKgp9CH58Q==,type:str]
    discord-critical-url: ENC[AES256_GCM,data:bwaQNmRzstnr3OISFmE5O+/xc7XqivQXkCZlLFjvTeW9w9ngbyK7nGokrZHu1CW3qjpvH8eI8aPz38vH+PWe/Wdlq3+ilGU/priwmq9lkwYZr1dZkyWT8Ej8Q+PwpS0sG5RyfVQ8e8v41K1FtGjPt1/aE8AcGWJBoA==,iv:/5gv5dun7w7TrjgxDOQzjqX4S1RFQxoQ3VPyurtXCas=,tag:1yNvoaRgpFPI2jvORCz7Ww==,type:str]
    discord-warning-url: ENC[AES256_GCM,data:frxg5m7IXSCO+jZRoZatcpld/D3jRV52t00JHUMZLc/7UIsNcjWxxOpcMP6Xlz0UuENW9scdiRB49jPC/8WkB2wSILIiPBUFB35BUxhNd9XLjkgPagNDJuhaFlJFpqvY18ktSCYijpA8Nxj/xXu2V9TmPnBuqNpIOw==,iv:OtvIIXrzIeZK6RSbj8cE61+U8SXpCg2uXYlg6rLt0pM=,tag:uKeiF+PsqozXSA1RXpmBmg==,type:str]
    discord-heartbeat-url: ENC[AES256_GCM,data:GPxMeEuS8Ra+KBwzj2SLrWbizKHKxTu/eQEOchXNU3vepo6jnnyjuMMH9rbhPuEpi0YVsJIPUPF2ncdyandSHgq1qlttwQUIdJVRueAtgTAiIxKyN3a+Rb24mkCz64dsXmyBG2sc06RG+Um9s9FIiB0+H19yoP7Kmw==,iv:n2Kjpeo4dJsBUSyDuifrFsfoYsmQWDoc8OJBdmjt2P8=,tag:e5pWZVo/wn55fRH+XZAatw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmTnJwL3BFcnNIZThBNUJG
            YnRvUzZZTVVLQldEQ1BYdVYxc1NUTk1iNzFrCnZqalBlNkZwSDBWUm9HMWVDMEZ0
            MUZlTjJvK2dWZlh6a3k4b1h1V01iU2cKLS0tIG1GSy8rMmgvMDdlWVphMWIrZWFD
            enB6akNNbUY3ZVZNVlQzS1Z1enE1TzgKPv2vZGNCEnQ+qgX3glyTdueEPZNl9ZKP
            w5nHZG1sDfOi+0aU7OP/WfbeIs3HjenAXzGApy/e9LsEtcYi8kbVhg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T15:46:37Z"
    mac: ENC[AES256_GCM,data:KBicADfNg6zFjnSa32R7h+4UDLQivmnpjFD+iWXTTw0xpYtv5ZV3CvKz/ts/ET7BG7/B4ptjaKv5W3+Gl6XKx2g1O+LMms1Uo36wGJwboTtarVufw0COyPwauK6G2OwL6LLw+D9ImlTFOHmwGNe7cM1n30DCDIp9oheg6TOXaDc=,iv:VA8ppjgGfhP0/DRvTd2EFGQydmvFiLJy+ZclQumowaw=,tag:iYbxBuOE7SU1dqkEBkm+Pg==,type:str]
    version: 3.13.3
