# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
    name: adsb-config
type: Opaque
stringData:
    EXTERNAL_BEASTHOST: ENC[AES256_GCM,data:IQkzw14Cs6S8wKAxMKh+mKw=,iv:2ejOqts+AetrhxD50V8OlFgWUDBFmmIBXPTeaIvJCtg=,tag:AUHPgpgYqOX6gwQtasL14A==,type:str]
    FEEDER_SITENAME: ENC[AES256_GCM,data:ylKo08A0C5JkVA==,iv:riu1nHwyAcyMbJW+KGAAteWv0qwvZuKQl09LOKdvBz0=,tag:7zB8wEv60mm/Xl0XYQDdbg==,type:str]
    FEEDER_LAT: ENC[AES256_GCM,data:R6avoJiN8fA=,iv:FYbYV0nSHmuhnI6YGBHZ0UbHmSPsu7vjs8avrCGxsjw=,tag:0r6jMbIB1+iChrovIafzKg==,type:str]
    FEEDER_LONG: ENC[AES256_GCM,data:2B8Evy92XA==,iv:sZYKX9exPmaFA1Jk69dMRCld1w3SBDravJFoXnrJE0g=,tag:8dYIVyP5Qbc5s9uwDpiXEA==,type:str]
    FEEDER_ALT: ENC[AES256_GCM,data:tr5Q,iv:knO2RcagcwLTFyULcNkkNfG030bAllJFobB/QNbgk6w=,tag:0cxwpYcXH183MZySqejBUw==,type:str]
    FEEDER_TZ: ENC[AES256_GCM,data:aHXVyRLjsg==,iv:x/6q1YyNQyb1Fng2z0pXdVVWLQW96GXwcpOePLhmkSQ=,tag:MCXYsxlwXGFF2W2rsWzEjQ==,type:str]
    FEEDER_UUID: ENC[AES256_GCM,data:2HliEqPIavzzMfrWcM0c9IawhwErS18F2CxcUTSDCj9e5tZT,iv:BGkVcm7J1ENMDGDaahF5cz1QIAt0/Lxz8s03sRxc0II=,tag:VzuOWNEPYj6FRVdGsXmeeA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRE8rZk5vK3Z3Tk1XSklJ
            dDloM0piT0V3MGdtaHlzNnhkTzRrbENMaVdnCkhveGI1QUJ2MFFHKzZBUEs4b2lm
            N3ozbHl1Yjk4SmZrQklhYkJoQmNXVmcKLS0tIFpUanN1T3NMa2VvaW9EaE85b1d5
            SHZKcUZMdzhzWStINlR5SFdiYjEyK1kKU1BPIu5MsIcOtdb6QEQorTLEOXjfJgcH
            NzNpOaIezaqj1z5m9RMDX4MfE84+X6F2n+g3w0D/91JYBZmP5ehPtg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T15:15:43Z"
    mac: ENC[AES256_GCM,data:PHW+gGiqdbzogN3Uci/vmjVDMUjPSP30ZsFeNzpQjxRfxLyZiKKEBqoXwO6rDvTdBRknrXFnlbtmUQjyL1p4cqN75/OlicZk43u2rXY+gMf6uvbEtkZ84DTcFAbfDRPeaCYz5CHwyi9zcqxxzZIb00jM43NwVsZnZAkbzLKcda8=,iv:wEeQUx1ygRk4MXcq+WyXh24txGBSLuoTZu0jVeg54I0=,tag:xc75ZaARgxFTkAcCSndEKA==,type:str]
    version: 3.13.3
