# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-runner-secret
type: Opaque
stringData:
  #ENC[AES256_GCM,data:u+L95wqLoPKh5ccVqXP0BMtClm3mD5nnBfh5/5LPWtyXnmjC6PTp5MnnuRa8SOZKTfsM5weRw8FZR0QsUvX8i23hzZ4RlW5G7Q==,iv:8CKseJO4xXrSfkwtQyqx7tR5yhDbGHUhGOtgwKvwRP0=,tag:DPpWBVJIFGVfpmnL89/uJg==,type:comment]
  #ENC[AES256_GCM,data:4/r+ibwQPTLMGIP52mQpZ67tQ9Y5YDyT7grRv9x8muxaGX08Nu1eFGAt9QFGLoltTHZ7jFQtk7KUrDjc1gLti9ZcaTV0MWq0hQ==,iv:xgxC/rkOnL4kYZk5q6ckZOn0mvpZrvDCrGJcd2k7rtc=,tag:TOuZkFyjLbU9/lur++9yTg==,type:comment]
  #ENC[AES256_GCM,data:cJHvn9aL8G+Off2tKTezu+jfCmP+ujBRxMbtsRRAgJQcde9eZxglvy/WdctVI4Ic/iCB/+8BDEPnUGKzf7udnvscFh+2PNRLFEmkLJQ=,iv:/aZUeCaL4eNvevLWo0Bo3RpUFlLetAYWq4jDdlT0x8A=,tag:b+84vxDcNXG4qEpMfV+cog==,type:comment]
  #ENC[AES256_GCM,data:Oj5ZaJ/gxenGOazV45A3KiUTKyDGGzlVwQxTS01/zwFR83w11caj,iv:w9KdKZI93GOYIjyIfaCng4esmaJj8Bx3NJNrebBgkvU=,tag:yrL9XBm3J/1PYs0jVzWNBQ==,type:comment]
  personal: ENC[AES256_GCM,data:QmTxOInfIrRZfhRAnjx3AioyPrYQYUTXIxWlcRQ98B5gOMRjQmrDWqgUPqHDQ2S9QJR8zTwDsMour89OXbcFDsSZhlXBSb0MBybLUA==,iv:Wow4qPkEMa9/l6KbcnVThB1+pwQpMV49eq1jycDi22Q=,tag:aA7vEVnsIebUclok5r/zpA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzU1AzdGVrZnIxdkkrRWRC
        WmwyWWFyRUJ5N0tCWXB5UmFGRGc5d2NISmdRCmJaYjdSUlJsUnBrNk1OOTFJcUN1
        OVdGdTloQnR2bTczczBZdm9mOFI4cDgKLS0tIGxRMklJb3I3VHJRR3JKTDVFaFpr
        Z2lkYTNIRzVzZVg4eVdjR1RGdVZpWlkKF53tEYFQY5G9XGYeZrVnYqRuhzQQu2sl
        FSmlSAL/HAGMqyPrfoC4aBpYWlojw0wJ45kx/a4hT6G2I7ZwGru18Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-02T13:14:47Z"
  mac: ENC[AES256_GCM,data:rUob8FCPtqdY3rqdIp7cmCfIHndinlLzCpeQAcIZv7UEJL1BJMzO2TIcdmeBVUALBKNcYePMfVCe70OUyuf/X+Gwsvb4hR8a/BUzbIcncD4tLhq5YdUO9M3+TSl4RrCUdYhziXI7iu87A3SmPdX2U4lJIHFEk24Ogo4nr0yM36M=,iv:aV+IaG9P6TTec32mvP2VxoTtbmKsUrUOhszbnhk4Njs=,tag:5PjE5Dt4vd4BbkOnAknT7A==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
