# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
    name: discord-deploys
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:vy9BBqvr4lKkee86eXx9KA9rGIlZ+k0F4QaIa9o2nExR45o3NPx4Ep0cnGKWu21ty9lWGJP6DxIAcKciF2GXo0lFyVtjvDkYN3eJ1CDkLI6w0aqhWPoDnAn84osET0Y/9s0rzQn0OS1Oc739fLkw/avQ55vnJLPhfw==,iv:n7eUPetfOVPjx/RR+me0GxmbNbquS959WD93q4z9p9c=,tag:82rGdBd0Z6uijJIKEKWpYA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNzNtai9NYXk0czJmeEpZ
            S28zQkZSVkpBaS9ZcWJUaEU2NmM0VjE4aEFvCit5YXJNaUxyYWQwV1ZyWEJ0WUls
            S3R6TU40STY4MGxIbjM1T3RTN3B4Uk0KLS0tIEtTWEF5akVuN1dMbFRTQVB5WmtC
            R0dDUXNBMzhOZ2I0OGdrc3hrUVJMRzAKLANidrxFJMumvaSSMuYbk4m/aY7itlVu
            03kSPZi/0wETm0gbdPN3BgjK8J6lkM4ezjNgKVGL7Pfzwg1Ajmas5g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T15:54:52Z"
    mac: ENC[AES256_GCM,data:DlxtMrwyWxIanhjR2CMZEG8Ypxy3BgUxNV7xOhH0sSwjoeaiLoyydb4p9tl6+sY+REibHI5DT9XgiyawCuoyJ5YB/6E3OdV15D7CCVtQB3DR00rA/9QnWR58pFjChUt+btsmOga4fbtmPy2xeig6N/zRg3dCDj5l7rFxC6QjxPc=,iv:EN01mqb6K/vpYHi20yZRyM4nkf/FSTnjY7zMg0nDoNw=,tag:7jj3yvcl6pAjW3XvzrDP/Q==,type:str]
    version: 3.13.3
