# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
    name: flightradar24-config
type: Opaque
stringData:
    FR24_SHARING_KEY: ENC[AES256_GCM,data:LfjLopCIBYnhSq00SCcUpg==,iv:tJDaCvnh+IhOPSHFAcnWhLp0QcqjHS89tVC1Nf3cISs=,tag:NJXTQzrz4qVB06PmSoN63A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWVZmaHpUdWpXSjVldzFQ
            OXZhUkJZWEUzZEM1TlF2cE1haHlGZnBzK1NBCkV1cW9MS2tyRkRub2tiV216STlT
            RXdzcjkrcEhSWjlqSmhrNFFmekx3cFkKLS0tIEhXRCsvYytGNlZXS080c3NUSUI3
            R2xKVWpQYndYdUMrU1p3a2pKNDVVQ00KkuQZ3p8ysIqeNZ/SzcEEKaMj9DAMYE25
            LZqiU+JpP2kOmC3yJMizfh7HLugRATJOLXCI/u1Gn5nusus8mPSA/g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T15:11:49Z"
    mac: ENC[AES256_GCM,data:n/2XR/A+foYYa1alZrgl5hIgaN6t2jZe366NZFd1v0yjOSXKpP9FZun3eDvSGUmegI674rZu38jliC5JOP27aTpOnvL0n2QDm/k3W7vucnf8RlY44lPKInlQ3xO82SqIBuUB+breYNWBIqVitmGVIFINliUuP1VVL57XiXZVURc=,iv:DLPzYav7PP7AdjmlRCyejoBqZnrutZjhzz0o1qIlM8o=,tag:cHBrbxrnR0/6Mfrmsi9lYA==,type:str]
    version: 3.13.3
