# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
  name: matter-server-oauth2-proxy-secret
stringData:
  OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:fkHqxPc4UT49Txzz1kfrHSN7UM76cc048EonPump8X+GtlpX,iv:RAWuXtFdk/EV30vUAWiaHXKoAyBAKwPF+JwRdWoHTp8=,tag:Aq9iuiXSp/pZR8PtPSf92A==,type:str]
  OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:YKiNMgYZJ4u+JV3PEFUqRLZcrn9w6iPGs4RRONRAJck=,iv:ebrao53ruLBsqA6RKDgeMA8UbCBK9ZNPOpmPSin0/bc=,tag:Z9ffeKHVNOc7EF2va8yLrA==,type:str]
  OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:n8FAYdbioz5x7oUUo883GCUb5JF561y0kJSO//3oO4G1XKd+jWACF0QnKaM=,iv:SDqDR0934NY+Xbyrc36PdqPKCAhYYa5mrcGdXZtz0v0=,tag:NaC7d8nw+NZKnoeNStXa1Q==,type:str]
sops:
  age:
    - recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaNmZ6KzJ4TjFyNXBieHZo
        b3BjVTNrU1ZYS0gxVmhndFNpQjRJR3lLTEc4CjdNRFBMcDhwdFl6Q1U3a0ZBd1R5
        R0Z5S1VIVVI2dGFJbUdkYjNKMjFiaFUKLS0tIE1iYkNzUTh3OEg2dFFZR0dTU1pa
        cWwwN2IxdVB3dFA5eTQwL2R1c0lEWTAKefFRcW8+T/79a33qbfWiV1l7lLFue0Qu
        wKGelttk2qC6Aih3RWApbqrL4UKqWPL8gYAoIVgoJ9vvsNkgEo65eg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-06T19:32:51Z"
  mac: ENC[AES256_GCM,data:ARiJRbzPEullaNO4eTOvESrLy3VA5RnZXEUrYTnSrtVQgEIIe/0gAVuUYqevFYs4ERo2euy5bJShO2+KfRDp/NDw35INuq0vLQHTBgyhxfNdO3IkhMMnksdxGlYIAQ/YLH00r/Yo29VOQb+Hkss49q49BpqKr8J2ZRyaWFkFU0c=,iv:7KL4SfWiozjJKYT7jZIy9GaAFEi6B5zmzvwdNrhDjVw=,tag:z0wWiYCcdwWxmY9FGRYOAg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
