# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
    name: radarbox-config
type: Opaque
stringData:
    RADARBOX_SHARING_KEY: ENC[AES256_GCM,data:yvQl0BYtMDmG4HZmc4aHE+rabSeh4UknCVmfeFtgY7A=,iv:WeX04skTxJc2XmhDkfXw7ZD0/uyJJYcgt14Pjicf09w=,tag:ptaYfaLKjsSQUvKECeHhCQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwWC9sY1pjdFF3MFpLazU5
            ZXlnZnp4WWtUYUt5OEVvUkgzc2lDYUVLK2hrCksydEhJdmxHZ2lXUTMvcUJUakMv
            QTNZOFdFcG9SUko2VnlDK3JzckVTL1EKLS0tIDRra2NSbFArdStxVnM1aEljYjVl
            SWZleU5yd0tIeWFiMFVqdFdSWnN2ZkUKx3hrfMNO/jlMWKC1rzl/dwbBNwvCuMiM
            1W/JiWJ1EEYDjnxQUOoGoSDD1ImtykOfr1pZftlKo4OnniLaT+tGPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T15:15:29Z"
    mac: ENC[AES256_GCM,data:hXYfZTIG6PYblbtJEUF0j+ifD8jNUTs6iLE7BLSTV+wFMcYhyM3uvO/rBPtA23qiG+AmrNlAvb+yGYHEcSFunp1wPpGsXSUa/fFFYC9r4tpXLAg1Qrn44r6jsUYTvsTNKgEym1uJPDZGg4S8ba4BFTSt/21+1wrJyk4fzTd1sZ8=,iv:h06CNL3kAvZo2JAOoNSBhEmtxPQd7rV9JJ4cGl9ETQM=,tag:KLgXzHH4e9dSAAItWaMH8w==,type:str]
    version: 3.13.3
