# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
    name: mealie-secret
    namespace: self-hosted
type: Opaque
stringData:
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:BRNRs69ka4MtjehAJrABV3dhjpjaUvnNK78CzVMFDJWvIopf,iv:FTctthO6BvKDXAVrEl1Yo6LJTdGcIoghwaevdUVKJz8=,tag:Eu+n7s/zlmt2Hx0T+Kokww==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:NM59StlfgKvnbitC5Sez9i0BFC1xmvMEiWcesFoa6V8=,iv:b8dgN2RV4y1OiKwL3+jFlmAowtEa+3aOOBqZ/m8/NH4=,tag:byNe3iAEW34jo46VhQW9sA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6R2daNDhmcHEvUHlYWm05
            MDZVTkhOaE1XcXV2UDg5NUl6SmpEdmdCTWswCmx5ZlUyeE1pek9maUVOODA3Nm5F
            MXptNFIyZE1LY2lpMjd3M0xkaDVZLzAKLS0tIFkxN0Z1cVZNNmNFTUpZUzZ5S2ZB
            OEoydmdURStUMGlTTkpzOXR6ckZmd3cK0rbb7ytCe83IUIylnVx4yi0V/KYzaH09
            pWEx6/kyO61Qa0CWnWQvdSX704oIzNNPQDx77g1ghBPZG/NNd8Ku/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-08T18:30:38Z"
    mac: ENC[AES256_GCM,data:aGjEne9aEJ3V0uB02/R4PIOQKrfUotV1+q1n1QWZu9w9wxyPBoSt9BKvzZnZU89bB58NbSvgSdGGOKqa/SsuuPlaDiqmJ9+sejmFw9zBtdb3oZR9u4rpjJfMJxkOvsayugKLXjSqnx1QzlhMHDNIF24xU236mKl4oNtTsDyceic=,iv:QBARDpVXHKW+g7DiAi0V4vtVnEBzCiTu2PnGf8qsfVQ=,tag:OiVR6NaipVALuqZ1BD+VVg==,type:str]
    version: 3.13.3
