# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
  name: netbox-secret
type: Opaque
stringData:
  SECRET_KEY: ENC[AES256_GCM,data:rL3F6vNuq1ksGWJOJ058BGiYWkwVfHw6cNVKnDerj5IlnKauCj6R1kDobHq+2vVyl+t0leuy0rMh17UVXtr1Vw==,iv:37Ha82grKMtcFoXhHn0eUNEXspQGe6FF1MCCxP1dufE=,tag:4xd2F1mBfGj8mbnBcHIlQw==,type:str]
  API_TOKEN_PEPPER_1: ENC[AES256_GCM,data:0Dv8S89UJceUOZ4Js09CJ/0j+3vy4i5tQiLxd/mMYTAGXY2l3i7dkMrRo0hVSmHmf/pzKzFyNzE6jzHxiVqz4Q==,iv:/kxmMiE5JRPriDDMbylelqVmRGsOoXXRPFsFvCHZNqM=,tag:TXsai7weyqWB/9fWUJ287A==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:iKPd4neAom0v76ITgFtBbstkHdMpcsAgiNIYyto2kvo=,iv:yxQVipKf+7qSyqV5nVHPgCkO1aazDULVbJiDa//C7/I=,tag:aHxuw/WzyMf9/O/urF6nIQ==,type:str]
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:jEjADABBz/dcKHk6iZMuD7F/LyFSgVzIWk+nEhuNRjI5C+5M,iv:CM/0dFmLpILwRUizFcIky+ImxT8jO48UFZ9jOUQDCho=,tag:6DyC7Bydg2Eennhyg5EffQ==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:ycYYRNapdFPXT9vjRBDQsM+FrIbRP5pt4Ztk/n1czXc=,iv:SZMrOyIjUwRffZ4kcUUbV2Hmk9HRUiJUICbUf67x9yM=,tag:r0xWVTst3Goaif9nx9naRQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUFpSK3JGL3IwTUc4TmdH
        Z3l4SUxheVVKNU1ENWhaNUdEQXVrV2J5b1dvClJLb0NNY0EwelZKSmVwWXRzd3FU
        d0dyejhxYlJscVZTdE0yQnB3WWJIVTgKLS0tIFlCUVhRMXFiRlJJdWVCNEFsaGhP
        RlF4aVVMc0NEbUFNUFhsM29ENWFXRDgKj/xoTJrNmDBmcoWZkA+iRw+x9ROls8fL
        Os/NCN0Q4fe0PzErkadSkmyUnpoCW7XAMkgQx1YwSG7sWcT6ponjnA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-22T08:53:35Z"
  mac: ENC[AES256_GCM,data:TUXFebf1/CUkOqzBg/OKa1CTVmwbge+FAFd6EEd/hAZK17ayhf3Qp660sp5LLr5C528IC/YBBv/InS03wGvlQr/Hl2kaWOpu6hyDQVNrzNbd1rc3KxB1SGR72Y7s/pkoEuJjjeJ/HnC1nfZBTMnriU/nueAYQnygUDaNxwfIcAg=,iv:p6lUbWUYUHxDKOR47GmSG9CsoWgu8hzYG5bfhXZJTMI=,tag:PwqgEUNYIVYLW6Km2/c0+Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
