# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
  name: matter-server-oauth2-proxy-secret
stringData:
  OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:fkHqxPc4UT49Txzz1kfrHSN7UM76cc048EonPump8X+GtlpX,iv:RAWuXtFdk/EV30vUAWiaHXKoAyBAKwPF+JwRdWoHTp8=,tag:Aq9iuiXSp/pZR8PtPSf92A==,type:str]
  OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:YKiNMgYZJ4u+JV3PEFUqRLZcrn9w6iPGs4RRONRAJck=,iv:ebrao53ruLBsqA6RKDgeMA8UbCBK9ZNPOpmPSin0/bc=,tag:Z9ffeKHVNOc7EF2va8yLrA==,type:str]
  OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:XQ03SIH4CrQcNycTs0ISrgAs3AnDbHD+Qu79glMnSZc=,iv:CpFXB5I4XQW0iSQIYrDFkUqOpe4NLNr6Ap23IebhSKg=,tag:TDwaQwRRlrt1QNWvcVZiIg==,type:str]
sops:
  age:
    - recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaNmZ6KzJ4TjFyNXBieHZo
        b3BjVTNrU1ZYS0gxVmhndFNpQjRJR3lLTEc4CjdNRFBMcDhwdFl6Q1U3a0ZBd1R5
        R0Z5S1VIVVI2dGFJbUdkYjNKMjFiaFUKLS0tIE1iYkNzUTh3OEg2dFFZR0dTU1pa
        cWwwN2IxdVB3dFA5eTQwL2R1c0lEWTAKefFRcW8+T/79a33qbfWiV1l7lLFue0Qu
        wKGelttk2qC6Aih3RWApbqrL4UKqWPL8gYAoIVgoJ9vvsNkgEo65eg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-11T12:44:10Z"
  mac: ENC[AES256_GCM,data:W3mvfZ0hdXk/alPUdn+7GStTnCZoe/5IjQO19sbfBXUZO4QeSK0Y2wOPyEdsiMT3ixjuCTlheX+K4+jFDWYl+Fo/Won0a0+v3RWGw58T4PWhedol/QqsJ2RvFsWNtPD8C6SkT6rCZHUp6n8wmFm6DZ1YfZrbJ/LD6XlpgaNbNjc=,iv:1swzG+G1yb7LyRgbNF/IMzXA3eXSOYx9BDOt2IJCqKg=,tag:oMo+IjyX+bPnkl/kX8X96w==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
