# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
    name: airnavradar-config
type: Opaque
stringData:
    AIRNAVRADAR_SHARING_KEY: ENC[AES256_GCM,data:OIDdrIu/sy98rmfohzzRwa+S+TFV22Zih+M31r0w3Js=,iv:m8zzYnNuLaLd56OtLhHurCCj51uJtcHFDch/xjWBcBg=,tag:lzPACGitxX3LYSL7nSQIjQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrWGRpWENiNGJ2cVZweFZR
            YWZ4SFl1dVlScndaRzR6bkVYVlVBL0lOaUVrClplVjhuQkxqTllCcysrRC9BVDFt
            ME9YMXB6RWtLYW9ENmRLY3FIZ1ZsTU0KLS0tIFk3Qm1iZmxIUndHN2wvVlRRSVFC
            R2MwMkljcUY3dXY3ZTNpVXMrM3Z0dncK/92laklZEp1Eiqx/isjMKFQDsM8+H62d
            KtzQzu0XNkbdbeQhfs6rHyGuRrF5MGQX/5JrhAc6zyLPQKBxxyT/mw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T20:43:43Z"
    mac: ENC[AES256_GCM,data:XNvZkcgXBMEi0fvv/4wh3boSo5nxTBMziQ7oWKuaUdns71/ABc4FTXt7103SyiKG6V6Xwm2LGZVOC+hTYCDd9twyCooxQIYB5WKhhMAd3Te7p0Vd3jsRBNtV56xZqc1BxofWLnSsTsXEFH5aVtXZ8teaeIpIL4e4KupikzjgUbs=,iv:wVA8YEjrfzwmef50Ms7mwRhChcRwSOqlaWD6/n39MzI=,tag:ilmXLy4PvOHt/y+ZENIHTA==,type:str]
    version: 3.13.3
