---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
# akvorado inlet/outlet/console - configured by the orchestrator
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: akvorado-services-app
  namespace: flux-system
spec:
  dependsOn:
    - name: akvorado-orchestrator-app
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps/talos1018/akvorado/services/app
  prune: true
  wait: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
