# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
    name: adsbhub-config
type: Opaque
stringData:
    ADSBHUB_CLIENTKEY: ENC[AES256_GCM,data:LHtpIITF44VU4SDTSDgp2H+CIxIYfbB0/unz2x84jETAA6hkKOSregHQ8rFpcCEeW3vbEDl8ADblX36T+ePiF5YQcJPl/2H3nzPVa3cOzXxn9e3LcDJIKXNVrULFsfdYSCE=,iv:MfyeKLFQig8e1clUy/ltxha26Cu/4pA1Uwop5JgN5pU=,tag:oBRZEfAGkhCyxs7rNLz+ig==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWWorUDhNYzZvWjM0Y2lr
            RERDaFFGN29JYWRtZEF2SEN2UEd5ZitDUFZrCmJmNXFDK1Q0UGZRNXc2VnNUVjFC
            Q21lOSsyQmxRV2ZCTG4xTHRlazlhQ2cKLS0tIEp0WEZ1K3NIeDVYWDJrT0tUS0M1
            TUlRbVd2Z2hSc0xGcWgydzVuMDJFcU0KjgEwrKLNqV60LLvAirBLm7vkHxk3GtO8
            cOOkODls8WNS08lSKDUqvntpuRKqztmQarY2LKG6C4Qssi3xmEd39A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T20:28:14Z"
    mac: ENC[AES256_GCM,data:Z/z2Im/z99BFHfox2+1opD6Ft52GA9uw83FuQd/5cfl3LMlnjDNCxDBqG33GBBQnrinzJjKqr98/axt4j+NisqQ68qCnGDD61A638YB1Jct4IvTrzvcEejlSwIUpnaBzMgmtLmylYwZE1UKSdF7tbIHghIPHMUGcWpXN4J1qE1w=,iv:J0UiT+uIta6kZBntphrdOb9I/cJI9YDtwifFyTt3SNE=,tag:brL9mH6Sz54b2wtf7SyFnQ==,type:str]
    version: 3.13.3
