# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
    name: planefinder-config
type: Opaque
stringData:
    PLANEFINDER_SHARECODE: ENC[AES256_GCM,data:KozSvKHJB8D916VX8g==,iv:GgP89PWAEm+e5cWzmwSavIJsTq7qvHpebmutN0mS5pI=,tag:TbWqgJ+x06XGndIZH+FiQQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRU0wRldnUGtPQnVUQVdt
            aml3NGU5d0M0WlVoemZzSEZUWTBnbFJ6TVFJCkRuNWEzMWVqOW9JQTVmTllkS0Nq
            a0dJbXE1NWQrUWVrVDY4bDZ0bGJZNWMKLS0tIHYwaEVvL3dxRC9IVWVHT1hCbHc1
            L1gyTDVZR3pBZ0hsS3A2K2FuWnhxSDQKyefK4DKcz6/yF4dUJ0KNeyzBtWyXMNZJ
            bbzR7Y8HM6CFPEIQEv6llPc23FNSY+k5gmrx8E6bel7LrJOk5eM08w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T15:13:15Z"
    mac: ENC[AES256_GCM,data:JwVtH5dCDGeBr3MZJqoXBY37VWye8Vs4vhxX52TJzc6900ixbZyz+RIYcxfdq3qEpB4vye65xXjAWAHWF7/yGSrFybUEgzrhIcsI8Cd7kP4br+Vzwx3SJM64SmNkIZ4orz10hTjEpS2rVVqJdvuElyr/t9hhiFx62Ik7gxcwQhI=,iv:k5tNa38VYv0KChv/tdcL24FuUqR9PdkBVJ29f7Dw3gs=,tag:nL68FG2dW33H1pafufFBPA==,type:str]
    version: 3.13.3
