# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
  name: homebox-secret
type: Opaque
stringData:
  HBOX_OIDC_CLIENT_ID: ENC[AES256_GCM,data:cMiu8e0rYPgjEqW5kI/vYsWwV/Ssqd65lKWeluct0zhDZzvp,iv:K+x4yFTXoIXQkBOeGBoaer8dkeOiYZgJOKnbhCOgqWk=,tag:LkwrQJA6Pg7dW1q/21x1CA==,type:str]
  HBOX_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:lob/TZSTutqM5fv1ke8fbuJQzvoJ2Hts5wdCah3DQ/o=,iv:45KWCUhG5G8Xn4rlZKuXimSYHcs6dONIuROhush2oOw=,tag:p2ShFkkoXDLFiIDBdgvswg==,type:str]
  HBOX_AUTH_API_KEY_PEPPER: ENC[AES256_GCM,data:msCnqyyrZ8PLI0Y0gOgJR0tTwqCeZ5SESpK3+0dWcgNFuSOw0puxBWzvnt8Orz8/HPnqtCRGj0c2x7SbuWVhsA==,iv:8bkbqsteSm5fxTTYbKZYbjGxcaAn71I8JrYZNcUQRdc=,tag:Xk6gIBkhkSjInz26z1nk1g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESHZKVDZzelRaSGd0dlhJ
        Q2tYWUk4TE5TZndSSkJERXc1Y3EwTkVwNGcwClJpb0FqWnh1NDFOVnRvbG5FOWpN
        TVh3Q0tIN1pyUG9JVDdkelZscVJNd2sKLS0tIHJWMFptZm9ZOGxDUHhmTDhwVXp3
        emFLbTBueG1NVGJEVURFZjBtd1NBa0EKghNbxbGmXyKubPhwBk7t3cUaG5HETS7A
        d02aiX4eYpiPUbYTBxw1tACdrjidMGSlvv/ISgWnCxt/TEzywVlXXw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-16T08:25:02Z"
  mac: ENC[AES256_GCM,data:zJm0TXqjmk+S+Su/h47mMJPaPE26wwf6M6CxoTESeA39qolLji4glLMYAHjwhNX5GlQuW9QnxKMPpaMnvGL/lI2UgE9hFrpOo1xO3GoYdqx6dT5//4q0F7o/UvxS/qwX6UdiExxogPwj9szwfX5dAIKhmS2/lC32550oIIqNC/M=,iv:BGkTh4at4l8KTWxxOvsPbEKiChbafAG07SIfvINJ4UE=,tag:f87gKPrsdg69dqlrvJ9zFQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
