---
# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homebox
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Main
    gethomepage.dev/icon: sh-homebox.svg
    gethomepage.dev/name: Homebox
    gethomepage.dev/app: homebox
    gethomepage.dev/description: Home inventory management
    gethomepage.dev/widget.type: homebox
    gethomepage.dev/widget.url: http://homebox-http.homebox.svc.cluster.local:7745
    gethomepage.dev/widget.username: "{{HOMEPAGE_VAR_HOMEBOX_USERNAME}}"
    gethomepage.dev/widget.password: "{{HOMEPAGE_VAR_HOMEBOX_PASSWORD}}"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "homebox.${CLUSTER_DOMAIN}"
      secretName: homebox-tls
  rules:
    - host: "homebox.${CLUSTER_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homebox-http
                port:
                  number: 7745
