---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app wishlist
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 1h
  values:
    controllers:
      wishlist:
        containers:
          app:
            image:
              repository: ghcr.io/cmintey/wishlist
              tag: v0.60.1
            env:
              ORIGIN: "https://wishlist.${DOMAIN}"
              TOKEN_TIME: "72"
              DEFAULT_CURRENCY: "EUR"
              HOST: "::"
            resources:
              requests:
                cpu: 5m
                memory: 64Mi
              limits:
                memory: 512Mi
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
    service:
      app:
        controller: wishlist
        ipFamilyPolicy: SingleStack
        ipFamilies:
          - IPv6
        ports:
          http:
            port: &port 3280
    ingress:
      app:
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Self-Hosted
          gethomepage.dev/icon: sh-cmintey-wishlist.png
          gethomepage.dev/name: Wishlist
          gethomepage.dev/app: wishlist
        enabled: true
        hosts:
          - host: &hostName wishlist.${DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: *port
        tls:
          - hosts:
              - *hostName
            secretName: wishlist-tls
    persistence:
      data:
        existingClaim: wishlist-data
        advancedMounts:
          wishlist:
            app:
              - path: /usr/src/app/data
                subPath: data
              - path: /usr/src/app/uploads
                subPath: uploads
      caddyfile:
        type: configMap
        name: wishlist
        advancedMounts:
          wishlist:
            app:
              - path: /usr/src/app/Caddyfile
                subPath: Caddyfile
                readOnly: true
    # Override Caddy config to listen IPv6
    configMaps:
      caddyfile:
        data:
          Caddyfile: |
            {
                auto_https off
                admin off
            }

            [::]:3280 {
                @static {
                    file
                    path *.ico *.css *.js *.gif *.jpg *.jpeg *.png *.svg *.woff *.woff2 *.webp
                }

                @not_sse {
                    not path /wishlists/*/events
                    not path /lists/*/events
                }

                handle_path /api/assets/* {
                    header @static Cache-Control max-age=31536000
                    root * /usr/src/app/uploads/
                    file_server
                }

                encode @not_sse {
                    gzip
                }

                reverse_proxy [::1]:3000 {
                    flush_interval -1
                }
            }
