# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  TIMEZONE: ENC[AES256_GCM,data:IEMoJHrqlPUgED0SxT5CiQ==,iv:LcMJk76OKOWUYi0a/NV3kUy4ABB625bH3fXeqKT6Qh4=,tag:YnsL2sBicFj6fAfypqL8mA==,type:str]
  DOMAIN: ENC[AES256_GCM,data:WGYbFDQ1kQckOqc=,iv:9jEa13gLSfk4fufes3DtppyYMu4P3dNgyUmaLmFiS6Q=,tag:1YaPDhlpkBWyrndWz92ERw==,type:str]
  CLUSTER_DOMAIN: ENC[AES256_GCM,data:CRFFoOtf51DAmNd4ukb1kg==,iv:OZrnaCvDcvwaVL7VYWLz8yL37HoxroZCjYztsX0PFX4=,tag:DXNhJHeLB3Ty4QnUFxuTgg==,type:str]
  IPV6_PREFIX_GUA: ENC[AES256_GCM,data:QF30UACEctH7gVJz7BU=,iv:aniYQfBnEHUkqgEt5F9mU5GVs/jNOA7yAa6sB1l1c1E=,tag:ISdwCD9A0yIzYAGQIXNpsA==,type:str]
  LETSENCRYPT_EMAIL: ENC[AES256_GCM,data:vIaVgPi9mckaqs3GpK1arQiJ23B0YBu4CS8mTA==,iv:KFIm5bVK+sW5ofMjAUFWr2RYZMLTFjy9ty+9fEFzU0s=,tag:tx7GIk+rF7TqcFQlbi4oBQ==,type:str]
  ALERT_EMAIL_TO: ENC[AES256_GCM,data:E1vCDvWZFx5QKzPnIsu3w8mLTb3NMPDKZCuung==,iv:1RDjrWhrLOlgkF2o1gT8L+fJrloaiBPAWCZcivJbK3I=,tag:ZiWCbcNY5RNlFsO/jt5PuA==,type:str]
  CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Z0Bx8RF+QgrAunjm9Bw9I1wHRObdAr2tSx0MZv8YjWvXTdQO,iv:/KrVpK2l4h5FMqGYSdL6WAJ58N05OjzmSnAdbLD1rwI=,tag:OAtg9UbSBm52tOUnDSFvQw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtcGRVV01nS09qdVlkN21v
        c0NUVEQ0clVlNVE0dXZvUnF3MThqSEhrMlNFCnFlZVJuTkRKOUIydzVjbGE3SUFl
        ODB3LzZiM0Y3a1p4VTQwSzhXcXpZSWMKLS0tIG1SR1RMQVk2Q2JVY2tDQ1pvYW1u
        ZFVTMzZxYmNwOStNRUlaa1liVC9ickEKHoIq3IaPBWolD4b/uBlqDN8CCE65ey31
        +LNye92W6D2LbPMyDSY5txOGY3lAaFkpthDBov2w2TfGLWXGB5rBcw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-29T14:45:39Z"
  mac: ENC[AES256_GCM,data:WRKjnQuxjux0O/iw3RilmWYilBTR0QAWUZSAyFpxPyrbaiB9pYv+QUmrk1mzIXcIfw4S3rOT2FnfyzfCObaSCxFW0OtcmsigZ4hE1CJvtxTR/Mm/PrAQC+UFUU5Nv8yLJL2NB7oVGyRnjztuFQWUNlFzE9uMFxRpofi35fRDNGE=,iv:/04PS9eiYUFrY+WXqcNo+ZWVj1ZoO5THUDJuwRWZXTw=,tag:mwN+sWIDHAhXfzhKBavU8g==,type:str]
  version: 3.13.3
