# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-secret
    namespace: spoolman
stringData:
    OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:igra9hf8PcokIdRKhgTDOg39KAUzhPlG/ukO2Y0A2mXNeM8k,iv:BLhnpYHtWn4Djpr1k392Y/JC3IfaSRmGS/vkFhkAzek=,tag:Fcx0KqgAKIZDJlTDNxxWyA==,type:str]
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:E4LgUZOeKmq8JJEm27O10AELizKTdq1kEZ/iKY7JL6s=,iv:PPd5S1Noy9X/fsIgPcSEppiQOO0IduWmLYmuYhoDdAw=,tag:QuSXQ46/B6pm3N1NCzMT8g==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:ioWe6Ib9yYW3YEDD9xyDKzVteZvEDURdQjFA0EyYIPFHueMF8ivjlekOAgQ=,iv:q4E4Vw181LGDbL/yVC7rFnSxlLmXcGdXHJEL4k5U/gw=,tag:lGbEuDGUXC2M2zwQ1TF1+g==,type:str]
sops:
    age:
        - recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0OXMvZWhBd3h5eVVlOG5G
            SVNRVUYzR1NOU2lpTEtEaGxlWkN6TVBZOG1FCkRGdFpnMTZCVWhHVk04eUNPczd2
            bzNELzhObVFuZHdnblNrMXVtWm5hRWcKLS0tICtGR2RrbkpQaDIra3laT1ZTeGpl
            WmpsWXF6ZXBMZDRjdmNmVmFTTmpFc0EK0ZsBvmcl3dRvn+D7avzZeeAJjoU5V8AX
            aJ9ftj8JfasbzV25THxggnV4qXnEtbCjNTOC3bRpYFhQLjDzq+s0Ww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T15:15:15Z"
    mac: ENC[AES256_GCM,data:n/EMn3OHcOmc0z/d/qUXKvDiNCHO3RI6z9W9sbyWy2NkkP4jAQCUaY8vXfcXB3YmFZHD6iw9ArJMOoPWl7FLJ6Zvm/Tcs7s+mAgsNRMPJYMfgyu/tBLtGGDKn0SD9B0fZcmxINLxP2X0rpA78T6evR5dljBKjDSiISplgwLBIAE=,iv:HJFPqtIDg6rKeKzX61BAJu6Vf7LPikgGaePWmg1/5hM=,tag:6kALbic2GmWRjgC4qBzhGg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
