# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-secret
  namespace: spoolman
stringData:
  OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:igra9hf8PcokIdRKhgTDOg39KAUzhPlG/ukO2Y0A2mXNeM8k,iv:BLhnpYHtWn4Djpr1k392Y/JC3IfaSRmGS/vkFhkAzek=,tag:Fcx0KqgAKIZDJlTDNxxWyA==,type:str]
  OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:E4LgUZOeKmq8JJEm27O10AELizKTdq1kEZ/iKY7JL6s=,iv:PPd5S1Noy9X/fsIgPcSEppiQOO0IduWmLYmuYhoDdAw=,tag:QuSXQ46/B6pm3N1NCzMT8g==,type:str]
  OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:84DG2badA6gnqb0xyn3mbHySP4C1/nbunJK/PMr26mJbspY0A2GkjwJLHFU=,iv:bxAPWOsxKB4awCOvfwpHBdGuWZHXnl8DGEoGsvP3AOg=,tag:wXrz4cPeOJUI8+BQokXxSQ==,type:str]
sops:
  age:
    - recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0OXMvZWhBd3h5eVVlOG5G
        SVNRVUYzR1NOU2lpTEtEaGxlWkN6TVBZOG1FCkRGdFpnMTZCVWhHVk04eUNPczd2
        bzNELzhObVFuZHdnblNrMXVtWm5hRWcKLS0tICtGR2RrbkpQaDIra3laT1ZTeGpl
        WmpsWXF6ZXBMZDRjdmNmVmFTTmpFc0EK0ZsBvmcl3dRvn+D7avzZeeAJjoU5V8AX
        aJ9ftj8JfasbzV25THxggnV4qXnEtbCjNTOC3bRpYFhQLjDzq+s0Ww==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-27T14:56:04Z"
  mac: ENC[AES256_GCM,data:OYuaCuoG0OrhAlYBz0SavS1Hp9utUfufrZJLIbxruYky23fYH6O1cWNfuQjV6IVBA0zUnqG/uCNxEvVL1f71zMkmPH9D3PPQrCO+aRKZbkLZWMjuutvQD/AlXZL/ZH3E+Lx/q59+PDQK2X2xpqR7z0/0jQazViNh5TajkhSeICE=,iv:mlcRpakag3pQZgwFNIDOnbmlsP9INuk0MaNf1y2vu8E=,tag:3I1NCr3m5nRtZTtN6ZqxMQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
