---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./kube-system

  # Network and Infrastructure
  - ./network

  - ./security

  # Cluster lifecycle
  - ./system-upgrade

  # Monitoring and Observability
  - ./observability

  # Home Automation
  - ./home-automation

  # Self Hosted
  - ./self-hosted

  # Developer Tools
  - ./dev

  # AI / LLM
  - ./ai

  # Web Services and Apps
  - ./homepage/ks.yaml
  - ./homebox/ks.yaml
  - ./bricktracker/ks.yaml

  # Media and Entertainment
  - ./media
  - ./minecraft-bedrock/ks.yaml

  # 3D Printing
  - ./spoolman/ks.yaml

  # ADSB / Flight Tracking
  - ./adsb

  # NetFlow / traffic analytics
  - ./akvorado

  # Development and Testing
  - ./podinfo/ks.yaml

  # Guest ns for untrusted
  - ./guest
