# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
    name: isponsorblocktv-secret
type: Opaque
stringData:
    config.json: ENC[AES256_GCM,data:dXNwKT/e427pmPPSPCV+Lid8RKStGiw4uGoCEHsZHSOrD9zcTYMcTy3m5uotugrq4kKz/uX01DMu4GKQjcNcdjtC+N+vN9UbapP1GukRhbEQcK93CBbk+4L01rCWqx6YfJAa7RYUv0OlRDUP1ybHrIUihdkvu5s8+k03hv6ql5uCgpyRMKeRXBNBO7eUXnQ90AjgR2nL2bcvRTprYysOVrmgBt65YIEDJw9nh+2tzikAXHjtJHyL8AKGt1/6xTnHf2TbdhzdVh8ZFvtWderMD++nWfbQvTgnRdnymrHacANbpy2b4TVm+GrSb2DZXSePHcoZ78ZZwCxvtdIieTH90XJQOQEoEClpEEMZTDNDwKBGGjC09T4UijJWGkjZaOC0fvBDoxJA3qMsJjoQDn26E7nn8lFVLB6o4sLs/usvZuBHa7g7xSWqZmo6/HhFmg9se6vwVBLA82HAF8ASPeYDAGWH2tALrpQIhlabR4rMQBVnU7I=,iv:Wkisjunmcpy/upiqpcntQd77874xRk6v6AuBLxCEfBk=,tag:0ZgwQV0Q+6Kfwlcudq8jjw==,type:str]
sops:
    age:
        - recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLS0Qxa0FmVlZSK0FIY08y
            Rjd5VmFHQUxzN0libndOVERhZUd4YXpBaFRzCklnZUh5WGJ6Vk9wcWE4UThZVEo2
            WDB4UU00cW8rTlJranp3dGlMQzIrY3cKLS0tIHBSZzFNR2xZcE9yN3pTQjZrakRK
            TUxCemdrNEcvemJXL1NIYVB3OU9hSmcK867Y4IYMvfxtUECsXf55w0OiWlo6gXdy
            e1LczRS97o8xEju0O2FJi7ptGaYuWpayRz6wW2yoX2Vb22KHSg3Dqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T09:27:30Z"
    mac: ENC[AES256_GCM,data:hXmYV8AinWwp/n34eUN6r4nMtxKqubh6zuPWqUJ/y+jAhBKyY9dgdNBfjoQuBwMBr/fjj84L7lVkPGU7moW7glQFc5HwZ0dlp2/SdVFBbPkYP9hWcZT9TualTyjvTcl3Jy8URiyTBjBaYHvQYxH0x9uMt2JoMonpprukzHOJnA4=,iv:z+JAB9rSiXfb0wgQ6Qks+PIbPtCfiRxeJiCFuXdvzUY=,tag:t0tsbeRDh94zj0x+KDbB8Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
