# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
  name: isponsorblocktv-secret
type: Opaque
stringData:
  config.json: ENC[AES256_GCM,data:NunlwnTXrNvGU7Tt4pHfjydroRxvQCM9oqy+GWiVxQjLEsTcsZJWq5ks64hhIoBtGUBEqCySfYcJIHQKBGApRwJKZ3X09nCr4y6ZQVdVldHHPXzGJYPiteG/+XzWAxTnP8LqK0aHLY2Jcx+3dVzpuSWvRSGyS48/ZHroRzpmcIca9SKId0tVAy+jJj44II9RjGsxbnmVmAj7Z+/t8M8YF4WBoslNnXjPxWxsdaoIYzT5sYNy9T5OOH9tmtmYOJzKgnjSN/uZjRU5nD8PFUdSUKn3K85h8l9+cp58mID6k5vcuOtBk2XXiyZqHttMOqATmPgJg11o9NJgoW6d1zyQnKV0qTZZuMijs4jeuodwad7N712hjOQW0A+TqHeWdnshqya5ay05K29Uq7rn9h+9ar1BC2JGeu9esmAk/cFQQ26PA2mr8UIOLlHzzAeT050y40QZMRoOrX0vpe8WkxaRPKNkxli/qJM1D+xwXkTEmt6oolRx,iv:nZjbbu0ZDpBNwbFhAML+/+a9I6DGXOC7brX98ebI+zE=,tag:g0rFyH8DvOYdX+veREd5Lw==,type:str]
sops:
  age:
    - recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLS0Qxa0FmVlZSK0FIY08y
        Rjd5VmFHQUxzN0libndOVERhZUd4YXpBaFRzCklnZUh5WGJ6Vk9wcWE4UThZVEo2
        WDB4UU00cW8rTlJranp3dGlMQzIrY3cKLS0tIHBSZzFNR2xZcE9yN3pTQjZrakRK
        TUxCemdrNEcvemJXL1NIYVB3OU9hSmcK867Y4IYMvfxtUECsXf55w0OiWlo6gXdy
        e1LczRS97o8xEju0O2FJi7ptGaYuWpayRz6wW2yoX2Vb22KHSg3Dqg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-12T08:01:49Z"
  mac: ENC[AES256_GCM,data:jDY7iLh5cP4FaagxbwzVQocjm9Fah1QFKBbAU5eOacvvt83uxxGVtepcogerpeIkSfOTaVp/cU8EH+QmB3n6uN41/Y2rLraaIKb42jWpr/gQpIdlvbSiluUtKwTIGpZ8tXczFTyY26S+R7Mw5XEaHrLHLtqoY0ckRkML5uOlsKE=,iv:o7Na5TCIip31X1lM0g9rEeK9a4QZHU6F6MjCDKbmzP4=,tag:1q6akYdK63XqZEbILo38Iw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
