# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
  name: esphome-secret
type: Opaque
stringData:
  secrets.yaml: ENC[AES256_GCM,data:35kdtxmec0iSUPT+fGjrtaCjSctacVwSlDs6NWeSAKiDNENppAHevZ3wVbRD9/wbjyGnWOBjkBP2/FYdf8ECsaoYBbwlTrSy191sbCOD6nfS5IBGMUpsetAFmMAw1J/K6IWmV2GjXhju2pQYni6FHVGfsRsFXzmOtypIshPRcsVfoj2p+fvRCykgALgAl3ISJDZRROVl7DXuoyayr0SzEo3v70QKgSpzh9nHUHU1eXc94i3EFKNsQKG/kj5Bqs165SWQxn/X6bcKxZzA34um3B3bne7Vu7/dT19n2MeNxw4C+HtBqKyK5EZylGLq0CXQPf3wxuzTUbVT42Ia7svXmgUNGAN84oNr6etLkIb62Lk7yr4qmzR9wa+rp2KQ91/kW7+7DKyyUKt5vhF1VRB3QtzIk9tf1Av9euKA+T17J7uhhaZyRSDke4HyrJbv7iph+ed1PobNwAb3uuIluck6aWlTU4ciTrEC8hGSeolhIBY6ZKeM+sQB6RnAbRbPRMiutUU2zXZ7lpLIg7wFMRtsokiKzTvBYJmVH0iJKUALRO8UT/wu+cJZxCSlrxmbwfd3vhP3vNNXzkoqiLArNbYti+FQzIQb78haeZVI96R3MjuMroQs3NMB7wekTD2ZI1nrdBh9kvoND15V3XgZaX8djiGoNZ1/ZK8teOfDMnFL+QzMiycZB0VLRIm3KFjgLXLjxqDhip/+PvlMKx3+yVJMPB2HBKLXTIie/ZaBH+jG746nafwk5r1+0A0j+6q8lrumsp+2K/IOmAVUAsYjB67JmBYCaPn0NLuZNxI3spA=,iv:wEz8xI2u3YN+LA1Bk6qfYV9tSR8BfCrg4Fr00cNQ9zg=,tag:yCf4rqBB1qIJBUKaEvOFRA==,type:str]
  USERNAME: ENC[AES256_GCM,data:G8ynJmKQj0U=,iv:nf+JWjN9lMQXXTsOV9WvwjHFStt8ed4SOcil5mZxeB0=,tag:uJ1sTGfkTqOERp++ItZOhQ==,type:str]
  PASSWORD: ENC[AES256_GCM,data:RC56O8CCqc8ZjVwHx45vMlgqAYI=,iv:OHeWfbC6i6+ZQ3+dLOgR5tRSy18bAJZbmRQ05sZKY9U=,tag:iQKctb6bhogb48GhV3WWog==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4NnJFalJWUFNZd1ZaUndz
        bTQzMjJpSmNNRlBGU3lhZEhVT2p5bXIrZTJ3ClhSK0xFY2xIK0ZnWGlaSVRocFBD
        bk5lSGc4bEZoNUNRaURXSVN0ZjR2Q0UKLS0tIDZIMHZzRFFjaC9tUHhadWZSL2lm
        dGo2Y2huWU9tTHpRRURMU0dCM0s2ckUKMxV2v8IDTqb8pkLWVFzs11hWZdEwngxA
        SNZVurVmyyYzVIJ/54HeiV1+WCMv6CRGD+rbL5btL6QsSzIKCJ7nwA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-13T19:48:23Z"
  mac: ENC[AES256_GCM,data:2YJYCaI/+wKL6huQoR9HiDThwQszjTc789g/Fg0+Yx+L6nxkMOryXEkvDWJOIr9kTxsHOmUXwS4/2HaGpQr+mPYRAcKQsO0qC9O9pcGBy8JROSNchfQzW1HmvfPfWhKbwxN2WE+pYeiNmKn8RUvjWjEZaJ+oMAb/7VB5VLpN4ZM=,iv:vHP16mtaR1BCq3XgYIrGQRif7cSJhRyC54S8EIcfvbI=,tag:JJsvLSrUHv0ybhOyAabsIA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
