# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
  name: akvorado-geoip-secret
  namespace: akvorado
stringData:
  GEOIPUPDATE_ACCOUNT_ID: ENC[AES256_GCM,data:lWtQxC/0nJC26E5FYlHaO7hGAl5KsGGtg2qWo79eug==,iv:g3GlWNvDw2e1YJd6+0aYkrTDHR5pa+7esZsYO5L8O3c=,tag:LVIsUgfOqPocCIZISefMEw==,type:str]
  GEOIPUPDATE_LICENSE_KEY: ENC[AES256_GCM,data:nYEVkqVsC/bzNAWbV6HyGDW6TAs+za3H08XBx/v3Ya0=,iv:Le1l3vOO0zZq8m4Ic+cPUMyfkXLboegtsrVX9R/5uYw=,tag:QSs8DsH3tbM3DuytfI4Vbw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvcU9rNHlmNm1OYWhocEZU
        K2hQYlZJRCtvN1NsbW96WGRkczFGd05TV0NZCnRvR3g2SUtwZjFvdkZuc0lLV0xh
        UnpDOUZZS2lnbUc5RmxmZzVBR3ppODgKLS0tIEM0ei93d1N0bXpYWFpLYTFyMXZH
        a3hDeURyc1NEWXF5S2k2czg5VVBRa2MKKiD8RX9y+0Kgcshd+fJi3X4TdUkeIBep
        NQmp1RwvGUAfF3lCVTnLsKP1nkzACFROfmIHBttrlbfrr59aYP309Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-21T19:17:13Z"
  mac: ENC[AES256_GCM,data:xlbEzSo1HzHwAZFP8/T1GQPx3VIgEUL1uoyRoxEdYt4kY6ikxk2chcXw7djNElS/cdZgyubBaNAlzbHWmmbRHeRWLNfXELSZO9Ww2WBfbGxHzeukXSubndKL5qfPFUK1Cn7Wgp0Tm86hllBXlG+lF7XSAPxnEtVGhDTFPNJqaKw=,iv:omAVdev0ZyySU1w5KX3aWj5vHf7stFdPaPCjIXqGt/o=,tag:yg5gAFU49hJvBOIhqiecfA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
