# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
    name: akvorado-geoip-secret
    namespace: akvorado
stringData:
    GEOIPUPDATE_ACCOUNT_ID: ENC[AES256_GCM,data:GlYi3bZM,iv:puGcM3MQAWuONv5vlbaC/3fap1mfgyWjddbE9KnAgc8=,tag:p+YRiuo28zozvgQdY8eGpw==,type:int]
    GEOIPUPDATE_LICENSE_KEY: ENC[AES256_GCM,data:/WBfehrUnHmeem2gKHAgf1kyHBxZQPoXrCRRf5G4mdrz27zWnd1m6w==,iv:eRynUh2DyEiiomAzu1ppW9fa6tqsZwAiJWirqfQHBbk=,tag:YRHU0NSSt36FyPQiZyliDw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvcU9rNHlmNm1OYWhocEZU
            K2hQYlZJRCtvN1NsbW96WGRkczFGd05TV0NZCnRvR3g2SUtwZjFvdkZuc0lLV0xh
            UnpDOUZZS2lnbUc5RmxmZzVBR3ppODgKLS0tIEM0ei93d1N0bXpYWFpLYTFyMXZH
            a3hDeURyc1NEWXF5S2k2czg5VVBRa2MKKiD8RX9y+0Kgcshd+fJi3X4TdUkeIBep
            NQmp1RwvGUAfF3lCVTnLsKP1nkzACFROfmIHBttrlbfrr59aYP309Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T19:23:32Z"
    mac: ENC[AES256_GCM,data:W2liZOR3BBkn4bUFLPI4iVqM+tBvvF3CNqH/AVV0VTvtWVBDR4JX/GjOx2hrp2oT/lAEI7ZbGelHq0lNm9tW+QFnWTz2U2s5Dka5BExp4KDw1PnBbu7RxeIjFnIVdYf9Gub93hESmJN97d1ZuCcyHWLajBjPLmyDPsmjb4fQgRI=,iv:CcX3y4PRBivCM5t/TVzJ8/1lXB+9AMXmot1HDThlid8=,tag:J8k/ryrYgb/WRBjsCy6csA==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
