# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
  name: akvorado-oauth2-proxy-secret
  namespace: akvorado
stringData:
  OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:aYT9YTmXcB6e4pXfA3mpz+OqqOASLCTIDRM49VC550q0oBCo,iv:F5RiQy5QIDZdC56/rNEYC8Xkwl4LMb1utpHtEUYewAA=,tag:84EOQdVAFMaBxqRecowA6w==,type:str]
  OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:6aKQWIY31i/igdygAyMvLgC1Fs3ioCGu2p/75iMOOeA=,iv:6cPW6Trs/e0LFDyGnkc4MtqzSUJG1OGtW/mR11Mm9v8=,tag:VERLSP5Yp9586ydUmsrlwg==,type:str]
  OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:TS2EIBM66V3zXYx7NC3BRnaGLti6XczswcKaLZqiX7xLl9CVnzjpZUT3ILE=,iv:XUgAygWMSqelh264eYM7fiRcpLFBRTySBrvpTfUqf5M=,tag:no8b5aXf+JPfSW0OAc4LRw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkMXZnUmJvUFRXSzI5REJu
        OVNHeDNDUjZRM0haRmNNbmtSWDU0WEV0RjFNCkxSU1M1NGlKeVdsTnJZRXZpN3ky
        RElqczFCbEh1blNpTWFyYXpsd2g4QjgKLS0tIEc4TG1INEFzd0RsZUtKajdodHUw
        M2djVnAwUENJZFFRdTFSTHptdXNmNW8KPS5ivTRbrapFtEP2CTwDN800LDFO+VSz
        OaKhPukSe6q6UPVgo3TrN5w98Wx5T8mG8r39axK4sRGr9lIvnkcZ3A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-21T14:57:07Z"
  mac: ENC[AES256_GCM,data:/XxVMVe5lDdMJvxiSVBosrfwiic4E6HbYNVFza+DSyp54SwuSEVGWB9HFky+p/+G1+SfO9lpUVwPJpTgEXEzEyM+Eze6OcvkcSEZA4/Pzjz/dPBPZH+fln+cW1/kTy7NJGSbNrnMsmsLmk4QKjv/JtqXPCPJ2LV6SSJJhjF4Yjs=,iv:hK2Cj0jKhL/SmndrpLDuNi0rdrJxXDpn82D71OeEQEs=,tag:687pQFU5MI4okIDXUsg8jw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
