---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: akvorado
resources:
  - pvcs.yaml
  - inlet.yaml
  - flow-service.yaml
  - outlet.yaml
  - console.yaml
  - akvorado-oauth2-proxy-secret.sops.yaml
  - akvorado-geoip-secret.sops.yaml
  - oauth2-proxy.yaml
  - httproute.yaml
