# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
type: Opaque
stringData:
  credentials.json: ENC[AES256_GCM,data:+K5jp69hUrrHjCOfDWrBnoMGRGnhkMHwkBqFrARE2tbQ3ppGLGQBSFAc0kYaB8eFAnYWLAtid8dGQbXHi+MjEnA0x+NMFUA0BS5ZRTsdh5FJ0KVnzuBEUJbSaqstsSQ5jw/S3rIUKW4lX3JcVHPGmNuBXfhGlctDTtW6jxqwPi4cWeIdTHsIlEVnmciCoDan+6raGojwhQDgLPFshJbZAWY=,iv:O438wf/KS3+BBFiwidtJkkbgQtprPD9t7Pmks7KRQn4=,tag:fEyT8EIqt88v+dZE+Eq9Ig==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZXhuL2FHdWlraGZ6Q3hX
        TUhrVjZVYnh1eWpVZ2pVTE5hM3ozN0s4UUNRCmhyRHlmRmU2bmdoZWU0MjJqazI4
        MWdxalN6dmFpbE9OQzFiYzFYbkE2ZE0KLS0tIFFwa3REN1ExVElHSzlzRHAxRGNa
        L1dtNWt4b0RpeE5nQVhEWGdadm5USGsKwCAj5zyCp3j2qKRoXFZRWjsYr/S+u/xR
        wjAGjO8qWWzaK4ueclD+z6ZFh0Eh6oQ3qX0ajPx9VlxRQUuG+b3wlA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-29T14:41:13Z"
  mac: ENC[AES256_GCM,data:v0nghRYx26G/itcfQFn8ILxtxbHo3qt8Jtzm15eCQbm0s1JD8KVqW5r19RoMNs8+99Ju+hU+7VSKhcnmFVPLdiIG2K+76V7iahJ0jbLrQvUacFnv0dZbxDcfalbObZYGcpeF7SOzLI+r0/cro89TMVO6Q03axbhVn8HwtT0V2v8=,iv:1xEkNyHJzOLdFTmy9BpjxizjseY+8vHhEMw38HOP46E=,tag:0CG/BeVvk9ve2M36JrtMfg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
