apiVersion: v1
kind: Secret
metadata:
  name: netbox-mcp-secret
type: Opaque
stringData:
  #ENC[AES256_GCM,data:r4kDY/FUYFBpNLfWpHwXQfW9WskeR4T12DAHBBk9L0eqv+ynQsGYtc+bOKqgPL8CfZC/PWEZ+jQuAxcgm7gkTyA=,iv:R64FojsEbZLmWQX/CzvZk6s6wuIi9Fg8NSTfQmF3ZSw=,tag:zY0suAg64t11kkKhfupOCA==,type:comment]
  NETBOX_TOKEN: ENC[AES256_GCM,data:B9wjArpylWWaC05PyZo/TZlZndvycjBG6suampHauBgzbM0LAiu3qY+pkOPshD4LhaFtPUn0VaLz,iv:2U+7D76RZmskNZ6or4B58tDzZzFVVWWs6SzcQn+NYVM=,tag:GBN8EF3fTXwsGzsg3mrq4g==,type:str]
  #ENC[AES256_GCM,data:fSQVk0pwdq8+8N3CQ05BtTWrkbSH78v7olxE0Z9axvuTf72rq/U6OQdy7s1zGlHX8InjqRQ4hZCF/g3nCxwH5gSP4ce8IXfaRNjs53K+THQSRhhiGjRrmSv9,iv:smgRWFPGEoVNm8LfMEyj488VtOBI7jF2rHHRHYB7bGo=,tag:DJX0wtNbPSyiQPLNrWtvWg==,type:comment]
  MCP_AUTH_TOKEN: ENC[AES256_GCM,data:ZmSGBD3BvhmQ3DTELleC904yuJqZmEs8FFktmEmgw3VoxqW9098MkkiAbYff+RdSIqhQ018Hntgu37enk5JZYA==,iv:R4+RZGhLq9XRIzwjj0qPGka5wzFtSnBoy2/m68FnYZE=,tag:ukQhS4SMp7czVtv4e2sIzw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAraTlUMXBhajlXZVpiS0Zu
        VEYyUlJiUU9xUCs1TWo5NWVtNVE0eHlhaVQ4CmtOQnViWUxONjUzR1Zub0xCd1JC
        dHZsNGk1SG12TTdhaFRlclBJaWttQkUKLS0tIExjSE5kckR5YWZNNjRIMDFvcC9n
        UUZkUU1xbWk3VjVMbDhYWmt6L25pRncK8RpqcAubehpFvX3+Bi2qRt0CtRZuLIIa
        eepeF/GemlCJsIJ9pRJYzhXxe1/paYgPKOxoQBgNwQV4t+crv0cxFw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-09T14:47:11Z"
  mac: ENC[AES256_GCM,data:a2plBE6shjiWTxnLYLqw9mPmqxxAT2GQACk4znfpceYuok/2L9cIPRCdmT2ta50xl0GKKUch7gvOwwzxZalBBpGXo849TL+yq2h0jYHNAHmEAhmMbKmvP7m3A4xw+vVJClM/J/SltLF31y3vkiSLWsHTuZWev2KS1w/9svvrlfE=,iv:KrOEVED5cBaU69bL8yALmkS2vEuezFVFXVwzhkHyCxM=,tag:O9UjzckT5qfh2+ynMbMG/w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
