# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
    name: opensky-config
type: Opaque
stringData:
    OPENSKY_USERNAME: ENC[AES256_GCM,data:VWZUscFJNhg=,iv:RexIRHNYRR2JwLXak4maJl3uNkuop5HtHYjh4906mb0=,tag:johhizda4xjkxarIK3R7Lg==,type:str]
    OPENSKY_SERIAL: ENC[AES256_GCM,data:yiRPYUk2PDvtOyg=,iv:S6Iue+h0PSsr5QFMLIUsgjm8ny4hjjIYkRMF1zHAFnU=,tag:2iclRrcC1BsI1ZooZnqs+g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBNWpCOHFneVJMK05yUFUr
            RC9kMTV0OXZEZk4zYjZIc25UenpJWVVibVZrCmdSMHdzV1IrWTV4QU9Cd1ZCUlB0
            NHU1dm9YbURnUVRLUkdCalhmNjBpUWMKLS0tIEhiVzVQLzZ3eEdTYnNucG9iTElq
            aVViL2FnbGtvWlhTUUJiZU9EMEpJVTQKx3lMig/LpDTbu1D9WtnlcIC6CTml5Hn5
            5bPWxp8e+zQEnYZ7+aV2U9UQi05LC8cdQa4aSX8fJ+zqwaze4Yi/mw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-08T10:41:23Z"
    mac: ENC[AES256_GCM,data:R5byA2cunKY4vX9iyfnHk2XFmFwW5PkWGA8fNn42AR9qe8XyFUsofY7HoQncSW+JW0+P1cHEGHVggGL5+aaDtYxIwcq/TuzqK63qxsHJZiA3/tiLVrCToDoYMB+sKB/WHowrCe5mv7/oMeAx6JQVsPW8cUs7jbjb7HxmdwSr+Ig=,iv:ZXuGD1tKKs9IRgZ5lEVm8EKuATkUp2wju7yMsoQ+tX0=,tag:xv4Dc+umxySAJIZNrr65YA==,type:str]
    version: 3.13.3
