# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
    name: opensky-config
type: Opaque
stringData:
    OPENSKY_USERNAME: ENC[AES256_GCM,data:VWZUscFJNhg=,iv:RexIRHNYRR2JwLXak4maJl3uNkuop5HtHYjh4906mb0=,tag:johhizda4xjkxarIK3R7Lg==,type:str]
    OPENSKY_SERIAL: ENC[AES256_GCM,data:wELpWPGsEOA=,iv:G/qIYk5rtIQgX7Sh8s0er7Qr1ecaXyZvOsAx/4HBiAU=,tag:DQFxx8Y5gifpbDf2yatv2A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBNWpCOHFneVJMK05yUFUr
            RC9kMTV0OXZEZk4zYjZIc25UenpJWVVibVZrCmdSMHdzV1IrWTV4QU9Cd1ZCUlB0
            NHU1dm9YbURnUVRLUkdCalhmNjBpUWMKLS0tIEhiVzVQLzZ3eEdTYnNucG9iTElq
            aVViL2FnbGtvWlhTUUJiZU9EMEpJVTQKx3lMig/LpDTbu1D9WtnlcIC6CTml5Hn5
            5bPWxp8e+zQEnYZ7+aV2U9UQi05LC8cdQa4aSX8fJ+zqwaze4Yi/mw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T20:45:03Z"
    mac: ENC[AES256_GCM,data:rcyP8YTt5C4gIohJj/iKFtdZafXHp+Ty4RwQmUr5aY+aSXM+kaKc88eOBjfXB+PmNji/mrO01hAy7xN7/EZys2n7J/gDcj0QwSgodNNu3tKKJd2bnP/iP6gL6z757cpcbVzVi9Ko6pMghee8CLjmTyij/VOGzNRyfTZJOc67i18=,iv:9tgzlcd3dXhXPqqW31buU6MGIuDB3N9b8J4+W9q5q18=,tag:JWflJyKHfiiFjFkerFlufw==,type:str]
    version: 3.13.3
