---
# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
    name: homepage-secret
type: Opaque
stringData:
    HOMEPAGE_VAR_CHANGEDETECTION_APIKEY: ENC[AES256_GCM,data:aFgr0XrzMiNAmUJs7dqh7xLI4oyBckgg+GkiLlANzoY=,iv:XG9vPAUuFg14jxqHXgr+wzSlnTGRCfedTXo/dCJK8kk=,tag:IWmmPkWF1Ma69wprQyH15g==,type:str]
    HOMEPAGE_VAR_MEALIE_APIKEY: ENC[AES256_GCM,data:4lFTar4gAZnwACTPsidpoeKNSa1jmFTARvnNQVlidAurUUyToJj5GOUj0Msrosx36ThavZWKmrmOO6EWNYdaQcM/SezbPeyhifbVAjLxdxAFuy9yXyOPQuv07B0RWTd5diwxodVTBYPN5Q7EVnGBzWv9TDVBm+8/8veBmpCYHpHCvkMFPP+HVzNoZYoz3XO6NDhnlZHVcz8EVcDrHaavoGKgMJqUux3ZQP31ggtSsOIR1RDp2DlgtFlVq68gwsdQBpvwi6UeoxQxIzyPTHsNHDNCvKdYiJq089DMUJtik8nsb3fZ7j0o6TWs1jH+uUxUIKXpaUFP2sc=,iv:cHRnGlJuoWGXCN4yzUeSS5810dTyv9QWmtwcDAQl0gU=,tag:KpSD8WwiUYCX5Apjs1P28Q==,type:str]
    HOMEPAGE_VAR_PAPERLESS_APIKEY: ENC[AES256_GCM,data:eDYoZIhIseRvRXoHwQ2N9QRkiDXya0zY38uwJS4kYfGBTSmxPOGPOg==,iv:HNWClrg6QoTynQNTBrmNlMA0lNINd4VPItexXGhGBGo=,tag:rz3YaqWZZ3uXe3lve0JuaQ==,type:str]
    HOMEPAGE_VAR_HOMEBOX_USERNAME: ENC[AES256_GCM,data:10rFELIgUhUyan/fBxuSUsFreqKeOHaRjQ==,iv:2Iuv5kGADq5qNCJTi4WakMfBTkdzlqYM9BI7YjaE8Rs=,tag:cSsUmnG2OmsSO3BpMmKv6A==,type:str]
    HOMEPAGE_VAR_HOMEBOX_PASSWORD: ENC[AES256_GCM,data:rCMOu/LMp0/edLIrF9MvzOHMJ4k=,iv:vl+Qsj4ef1ImEe0Ckg90cneJw7WoQo17w5gdL+s8cUs=,tag:AQHtUv7fY7Ovi3Pqz6MojA==,type:str]
    HOMEPAGE_AUTH_SECRET: ENC[AES256_GCM,data:O0leeAglV6zFp6rz5mUPTsMYxS4zC3WYepYr8ef/3xCMAgHaIsm3O2uu6oc=,iv:cHWOq4DoLy+LgqxvNXjrGYQNm4Hs3Asp2A5fiW0fskM=,tag:ovw+ChYXwDLtKCMSQAqHMQ==,type:str]
    HOMEPAGE_OIDC_CLIENT_ID: ENC[AES256_GCM,data:BtwKvzIjXqNgL9ibFlcYs5k/MQ63mjC/k4tEULs/haLTlj7/,iv:2s1yqFEQiEtl7UakeQgsyv4WLXos52VvpEpzLMLwQEs=,tag:A6dUMM72Ru78YlASOxVUXw==,type:str]
    HOMEPAGE_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:eZmcpM5iogg/GVDPz45jX6rpW+S0+RWirAHDv6ZAnjo=,iv:o4pdKLJvL8ohXz5pbx1KoThQQxo/+Tr23jQ8ksfgZ5I=,tag:O0B0nVZrQOVdTzXl7XhQqw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjYXFKRGJ2ejhTS3pDQ3FL
            TGllUDY0b3VaVGtIeE9EMlhUSnpXM1B4cHljClplQjV4MGZQOG8rQWczTnVlSzNy
            QjB1N1VkN0FXejk0djh1UlIwRkNmNlEKLS0tIGw1c3YrVGxCMW94eTRCaFVHbmRB
            enRnN0JmMFBQMDBzU20wT2FDVW9TMHcKZeSh4BQeq3jp0M77cPUgxbu5KnHzUBut
            EZabbYck1NbgIYm2UlAz/2sKTVpgqXgpfpDjKgIaX2WVET8408gQYA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-14T20:54:13Z"
    mac: ENC[AES256_GCM,data:gBLG1Uo+RZt03EjPOi0m0dG//9AMXQopWnc/8Z6k2Ou93jwsjEv3ICvoMGazTRRRz3YYdAjadCw+B69SXG0M1wcGHFd0DuYrWG74cm50PSIA1EitGyPa5+m1t5KBQtuO/cPyu1Mf+O+G9w2+qWq+X8QI/qprHNMaw3aOoBEO0ok=,iv:3IhhpXUO9GCH+zVoHgRC6VEddFIfLpwKjFuvHALMhGU=,tag:7o6oYN8VTU1Q+v6jaCzECg==,type:str]
    version: 3.13.3
