---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: adsb
resources:
  - namespace.yaml
  - adsb-secret.yaml
  - adsbexchange-deployment.yaml
  - flightradar24-deployment.yaml
  - flightradar24-service.yaml
  - flightradar24-httproute.yaml
  - piaware-deployment.yaml
  - piaware-service.yaml
  - piaware-httproute.yaml
  - planefinder-deployment.yaml
  - planefinder-service.yaml
  - planefinder-httproute.yaml
  - radarbox-deployment.yaml
