# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
  name: openwebui-secret
type: Opaque
stringData:
  WEBUI_SECRET_KEY: ENC[AES256_GCM,data:GkTF0lKqxqNyUvluQgLTQiKnM7+prkcno8rp2sKX6bEBFmIMGc3u0nE1O5YfmC0nBwgiy/SNv0iWNVLoBOGlFYHDeJhVdbodCKnAKRt3d1xitmjw4C5NC/bUYT7Qi7Fm,iv:BD6557QB6j/bSH9ZdXN0hmFgN9UOXWukWt+5YCKUQZ0=,tag:vQU0VLlB2tHcDY86UeWJMQ==,type:str]
  OAUTH_CLIENT_ID: ENC[AES256_GCM,data:lryTXSOXIPHFK7eUogOzPpfd1+Ex5ZjQ+/n5G0MXxc1MneP6,iv:rxH7GIBxcsOLZfnveXM5nldGseQM76EMgk0nEIbxS2g=,tag:rpMbTJQ0Jwf/BqTNiAloSA==,type:str]
  OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:+HuILxLqRV9ByXZr/DVlJ6vwdzwAPw3WdoZXx25qTDY=,iv:z7IgmvTL/4f5toN4cg0LT/krqgiofl3l4jmvfI601WY=,tag:DKlByL8GcNwmWnQQf9iqqw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2SlJDU2M2RE5QaXpvdWdX
        dk5SazdLVGxtUWdaNWlZYTd5SlFFM3FGUjBrCnNHQ28wVEhmcG83T0UvY29EcDF1
        T1ZQOGFQWVFxcXhzU1BuM0p2K0VXZ28KLS0tIHRJZi9hQkMrNjlCclVmME1JNVFG
        YmdrOHpkUUFKbTAvNFFwUUNkMW1weU0K9e6JcDkhWcILdiPeDej/qwrdqh40+nGe
        uZuF1PduURzPWCKUNU8HN8hHlj3byGb8QXdzbucY9QIDju35C8bDqg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-14T16:34:35Z"
  mac: ENC[AES256_GCM,data:zk6iGaOkDB9GvI7T0hyQTrhPscr63DiOf4U+cgdtWUG5evsyy0aPiXEV7Z1SUl6Fp+XIJ6C+niD/33kVIHb9ImyO7RVIYWp2/EATl+mn/Zn5vxw4U4UbPLQcxddag+O+X27EF5XXbwQ8wt+5CtLoeFGAwMMmtkeQPFgYHcaP1rY=,iv:DP92z6lIHOcU+LuYrxPFUDI5w5AAUmtLTaTZGJNwHpw=,tag:t00opw6Mfwt3NsPQVOsV1Q==,type:str]
  version: 3.13.1
