---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
      version: "4.6.2"
  interval: 1h0m0s
  values:
    controllers:
      home-assistant:
        containers:
          app:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: "2026.5.0"
            env:
              TZ: ${TIMEZONE}
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              limits:
                memory: 2Gi
              requests:
                cpu: 100m
                memory: 512Mi

    defaultPodOptions:
      annotations:
        k8s.v1.cni.cncf.io/networks: network/multus-macvlan2, network/multus-macvlan3

    service:
      app:
        controller: home-assistant
        ports:
          http:
            port: 8123

    route:
      app:
        enabled: true
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Smart Home
          gethomepage.dev/icon: home-assistant.svg
          gethomepage.dev/name: Home Assistant
          gethomepage.dev/app: home-assistant
        parentRefs:
          - name: main-gateway
            namespace: network
        hostnames:
          - "hass.${CLUSTER_DOMAIN}"
          - "hass.${DOMAIN}"
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - identifier: app
                port: 8123

    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config
        globalMounts:
          - path: /config
