# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
  name: akvorado-snmp-secret
  namespace: akvorado
# Read by akvorado.yaml via `credentials: !include "snmp-credentials.yaml"`.
stringData:
  snmp-credentials.yaml: ENC[AES256_GCM,data:3xER9sulxTX3KnMVqrIWjr8qK+2cbBxmELewBw==,iv:ssjd/DM4qVYVsILRN/zEAp46D+yabuugmr7R0iZUT/0=,tag:gjtiAIwfwbfEEawCe8driw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5dExnUVFnNVNXU1JmNEdv
        VkxMUHhBTlI2RktpUlBrWERSdGhTcVNHOW1nCmsrRjB5eGYzZmoyTXE1amJmVms5
        R3kwdEgvRVpTTGwrVVFQbU1iWENOT1UKLS0tIExFSVkybTRsVHQ0MnBEZk5xTk5H
        TllUMnNiZjF2TUp0cUw4VTgxVW5SVE0KVnwjQ1GNT6LH/9DdyD9AwItFGK3JfUrT
        o3EbyN9gKtVSk2LbA3fgspjDX1vvssHT5RCz4+jnUHO/3N8nr8JGCw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-21T15:00:27Z"
  mac: ENC[AES256_GCM,data:AjJ/VkQeuDqCrwpdXaRfObaqIfS34rEXizrl6MuJyxA9gk8xePVzf4/KN9TMrGSxme82ATGe1TJC+q4KfUKvq1OP9LSZ4NJOiKi7gRFEKrJCZ2amubNpNQpsuzfvdW4d/2Cnt04jJTJ2cFF9g9d+cuW7eL5putyBsp4I3ZZ2me4=,iv:98pQOwOXyhuMMNmPr+xS1vhjTt0WhjEnM3U82zT9wsE=,tag:PFsLmn45/aLWt/l7F7Eijg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
