# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
    name: akvorado-unifi-secret
    namespace: akvorado
stringData:
    UNIFI_API_KEY: ENC[AES256_GCM,data:3ii1ZJjWkqYkpdktX1jImqDnSfgsoUW+3fspm7geH8U=,iv:IXxDjbjiy5oUVPFSh6SSgoQEhqgWBt56OMzhuzfsDU4=,tag:ZC5AZB8tjhvUr64pSQu8oQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSGg3YmNwY2hKbFdKWVRq
            eFpDZEV5ZnNTdVRFN3NsRk5tVm90Umw1UHdnCkIyU3RTRStweGZJY2NSWjF4eGJ3
            STRQV3FpOEtpME0vampaZW9kVUNnWkkKLS0tIDFnWEJUZDV2dmREZUY3SVYvRzRy
            ckZRZjJOejA1NkYxNTRST0tGeS82b00K34sYgSaD+f9VrDNzufqaBQXrCzSEHnA7
            naEnVZFEacb5v4/UTFWpWgLAhwOmbZTl+3tdFbgd57kYsiIDSqEKzQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T18:53:54Z"
    mac: ENC[AES256_GCM,data:CQAhgG+TyAMI5pByIXpQmCZegxjE8yfcXy36sE2Brq9A5iQG9UrVgUzMwAkh0n+mNh5gmNtlQw3RSKlMvgP6HAK52cZvU/Fx/RsF94c5ix4M3/ZZl3fnx6BXpHuBXP/HHRcPGrjARwG9wukY1aspb6nCM8Y0ZwOjORNM0h0SCWk=,iv:Hecg737/9cWGHukelJQsPPr5YnKa3pOKCuogAt5vWUw=,tag:dc8ZWMuvtbBoWaDd7dCOtg==,type:str]
    version: 3.13.3
