---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: akvorado
resources:
  - configmap.yaml
  - akvorado-snmp-secret.sops.yaml
  - akvorado-unifi-secret.sops.yaml
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: akvorado-devices-sync
    files:
      - devices_sync.py
    options:
      disableNameSuffixHash: true
