# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
    name: gitea-secret
    namespace: self-hosted
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:lLP7PMexFNQGR4I=,iv:d6wBY19E8U+TK6n94MtAu3w2iQyVhHSlyWwE2JvE318=,tag:poOrUIKBCCmdZsTXx2A5qg==,type:str]
    password: ENC[AES256_GCM,data:6UU0vUH2BFqfsLD3tON0riCSDoc=,iv:LhZJP8O/4JYOGsiMYPoits8mfro3Bl6VnMotuoptNmw=,tag:ViAFJPiwOfGq7m9q8RpUQA==,type:str]
    key: ENC[AES256_GCM,data:snp032cbtrb4f18/azR2d6I6LbpEU+YCVjC+zZkqM+6Yd8iy,iv:KCAxknU+opOhIYhJPnyO2hYiKmj/cMjU3VHZFTIIIwE=,tag:cugX/x+cdAgMdbkhMRKDSA==,type:str]
    secret: ENC[AES256_GCM,data:To7euVRjkWU+pa9HPcKV58p6ZLV9dLsOvn/mAxRxt1E=,iv:DhhImWgitfjC0JoRxwdBQQOVUaqiL20KkZlyZyx50/A=,tag:duDQLuGRJmE9sbYneyZcDA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIYVJlRi9jTWNLMjJhclBE
            bGs2Z0xSSlJEM2ZUVS9xNVRuU0dBTFRmY2hJCnMraXMrNko4ZVVWeXpSMk9CN1BH
            ZTBGTkhUQlJsTU9vWklsOW9FWEd4NWsKLS0tIFdSR0tadDQwU21FckFNNUgrOVhq
            NFJKUEx2NkdSdnhkRE9iRkhxZXlFTHMK7GTI2fQzWtyyqgZHF8Z/xpYUKJKh7bgz
            zhcopgeDesOXSjLY150BM2w4rZPRo3oCCL8uEaMX7rcs9VfqdqriCw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T20:52:19Z"
    mac: ENC[AES256_GCM,data:sNrpvFyvoweSk7nR/CS/ZjA2Fdfqaf21BlGnUarcBF+oKOjdMyAJE3Phm6Y4ulTirMaYJYgEOZkAMOD8kCN3dEuTyeb89g73PkLP7VU/tqrV4e/f6kf74c4VFt9wbjmNLVHSTZcxJV2XRC97mGqRPXFECRtw25vDk/xswlJ193o=,iv:gWMutjdjr0TMDuLFY8sQ3FkbdXr2X+vG13hwTp7MSL4=,tag:+jT7nOwTBar37FWHLJubVw==,type:str]
    version: 3.13.3
