# yaml-language-server: $schema=https://json.schemastore.org/kubernetes
apiVersion: v1
kind: Secret
metadata:
    name: gitea-runner-secret
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:PdwrsY5412F2KIz0rXrq7MF6WhNV3h5ajCr4HwIbcXx1gY1JBjljHw==,iv:zb0jR+3MPuaBgn7Jzp6oXF+vvLVgKvBsXCj6cwwJze0=,tag:7ZimitG36Z/v7nzU/U/XNw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFY21YVE81ek9wT29MMUJi
            NE9VVVRyZ2dCcEpaZU9mNkc2U25PWVUzSVRVCkRORm95TldSbC9GU1Nib2FaTmdN
            d2p0M0I5MHZRTi9OcHZXOXgrd29wSXMKLS0tIDhUNjVKVEhibVEwcmg4N2Q2aDJE
            eWJtN0RZRCtWZ0VJT3dsdlJHVzZFMU0K0r9AUeUbkINsB63HkNpZlrV9DF5rKn/L
            gmnXXiQ5btnKxAWzKHRgJTTcM6t0rmDNOwcWK221X8bIZS+eGMM2Cw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kesma5f5dadlzdl5lzgrtxl6e8z8frf7njsfnlnprzan0lmzgdmstnd39u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-28T15:10:19Z"
    mac: ENC[AES256_GCM,data:l5EQcGb4aGgzXzyS0BNPBjpuL6FdrQXyp0AOve3M7OA1Coz+94axVs9ltwBC5cfNZFxDl8A0VsxhAtuL9AuF7C6Cm/Y2XVllu79Npd+tfWA3tJxp4VlBjJiNt+Gdy4uP2loh6BhjEbGi0PQ2QcyO0HKla3MwBjHfqTk9aav6L0M=,iv:XNZzQpN2qebF4O+jt7H7WFBqy7Bd/VdkmXSA/bfxzKM=,tag:i8SzQP9aa/lnmMvVbvvfsg==,type:str]
    version: 3.13.3
