---
name: validate-flux

on:
  workflow_dispatch:
  push:
    branches: ["*"]
    tags-ignore: ["*"]
    paths:
      - "kubernetes/**"
      - "scripts/validate-flux.sh"
      - ".yamllint.yaml"
      - ".github/workflows/validate-flux.yaml"

jobs:
  manifests:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Setup yq
        uses: fluxcd/pkg/actions/yq@a12b6e8ae2242f78513537c9723c17b480188b8e # main
      - name: Setup kubeconform
        uses: fluxcd/pkg/actions/kubeconform@a12b6e8ae2242f78513537c9723c17b480188b8e # main
      - name: Setup kustomize
        uses: fluxcd/pkg/actions/kustomize@a12b6e8ae2242f78513537c9723c17b480188b8e # main
      - name: Setup yamllint
        run: pip install yamllint
      - name: Validate manifests
        run: ./scripts/validate.sh flux
