---
name: validate-flux

on:
  workflow_dispatch:
  push:
    branches: ["*"]
    tags-ignore: ["*"]
    paths:
      - "kubernetes/**"
      - "scripts/validate-flux.sh"
      - ".yamllint.yaml"
      - ".github/workflows/validate-flux.yaml"

jobs:
  manifests:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Setup yq
        uses: fluxcd/pkg/actions/yq@90cfd68f4a9c2e7f919fa7333aad363523333496 # main
      - name: Setup kubeconform
        uses: fluxcd/pkg/actions/kubeconform@90cfd68f4a9c2e7f919fa7333aad363523333496 # main
      - name: Setup kustomize
        uses: fluxcd/pkg/actions/kustomize@90cfd68f4a9c2e7f919fa7333aad363523333496 # main
      - name: Setup yamllint
        run: pip install yamllint
      - name: Validate manifests
        run: ./scripts/validate.sh flux
