apiVersion: v1alpha1
kind: HostnameConfig
auto: "off"
hostname: talos-1018-3
---
# net0 alias for the physical interface (enp1s0)
apiVersion: v1alpha1
kind: LinkAliasConfig
name: net0
selector:
  match: mac(link.permanent_addr) == "a4:bb:6d:51:86:24"
---
apiVersion: v1alpha1
kind: LinkConfig
name: net0
addresses:
  - address: fd00:1018:0:5:10:18:6:93/64
  - address: 10.18.6.93/24
routes:
  - gateway: fd00:1018:0:5::1
  - gateway: 10.18.6.1
